// Static playbook data derived from enriched company analysis (34,841 resolved companies, 93,174 TAM)
// National baselines: D2W=79.2%, ARPU=€729, Penetration=7.0%

export interface RegionPlaybook {
  ccaa: string;
  code: string;
  archetype: "partner-led" | "outbound-responsive" | "multi-channel";
  tam: number;
  hubspot: number;
  active: number;
  won: number;
  demos: number;
  mrr: number;
  arpu: number;
  d2w: number;
  penetration: number;
  mrrPerTam: number;
  sizes: {
    label: string;
    pipeline: number;
    active: number;
    mrr: number;
    arpu: number;
    d2w: number | null;
    mrrShare: number;
  }[];
  provenances: {
    label: string;
    pipeline: number;
    active: number;
    mrr: number;
    mrrShare: number;
    arpu: number;
    d2w: number | null;
  }[];
  industries: {
    label: string;
    active: number;
    pipeline?: number;
    mrr: number;
    arpu: number;
  }[];
  partners: {
    name: string;
    clients: number;
    mrr: number;
  }[];
  strategy: {
    leadChannel: string;
    leadChannelDetail: string;
    partnerPlay: string;
    partnerDetail: string;
    sizeFocus: string;
    sizeDetail: string;
    arpuAssessment: string;
    conversionAssessment: string;
  };
  keyInsights: string[];
  openQuestions: string[];
  tamBySizeForRegion?: Record<string, number>;
  tamBySectorForRegion?: Record<string, number>;
  channelSizeCross?: Record<string, Record<string, { active: number; pipeline: number; mrr: number }>>;
  channelIndustryCross?: Record<string, Record<string, { active: number; pipeline: number; mrr: number }>>;
}

export const NATIONAL = {
  tam: 93174,
  hubspot: 34841,
  active: 6545,
  won: 8838,
  demos: 11153,
  mrr: 4769972,
  arpu: 729,
  d2w: 79.2,
  penetration: 7.0,
  partnerMrrShare: 45.8,
};

export const REGIONS: RegionPlaybook[] = [
  {
    ccaa: "Cataluña",
    code: "CT",
    archetype: "multi-channel",
    tam: 18993,
    hubspot: 8475,
    active: 1951,
    won: 2671,
    demos: 3154,
    mrr: 1319673,
    arpu: 676,
    d2w: 84.7,
    penetration: 10.3,
    mrrPerTam: 69.5,
    sizes: [
      { label: "S (20-50)", pipeline: 6175, active: 1315, mrr: 474534, arpu: 361, d2w: 90, mrrShare: 36 },
      { label: "M (51-200)", pipeline: 1190, active: 394, mrr: 421420, arpu: 1070, d2w: 75, mrrShare: 32 },
      { label: "L (201-500)", pipeline: 566, active: 135, mrr: 283476, arpu: 2100, d2w: 71, mrrShare: 21 },
      { label: "XL (500+)", pipeline: 379, active: 59, mrr: 132396, arpu: 2244, d2w: 55, mrrShare: 10 },
    ],
    provenances: [
      { label: "Channel Partners", pipeline: 835, active: 393, mrr: 443183, mrrShare: 34, arpu: 1128, d2w: 83 },
      { label: "Outbound", pipeline: 2168, active: 441, mrr: 321537, mrrShare: 24, arpu: 729, d2w: 87 },
      { label: "Inbound", pipeline: 3666, active: 545, mrr: 268167, mrrShare: 20, arpu: 492, d2w: 81 },
      { label: "Santander", pipeline: 289, active: 161, mrr: 118690, mrrShare: 9, arpu: 737, d2w: 75 },
      { label: "Paid", pipeline: 1207, active: 272, mrr: 118404, mrrShare: 9, arpu: 435, d2w: 82 },
      { label: "Telefónica", pipeline: 59, active: 25, mrr: 28546, mrrShare: 2, arpu: 1142, d2w: 56 },
    ],
    industries: [
      { label: "Hostelería & Turismo", active: 91, mrr: 62203, arpu: 684 },
      { label: "Agroalimentario", active: 69, mrr: 57967, arpu: 840 },
      { label: "Salud", active: 76, mrr: 45697, arpu: 601 },
      { label: "Construcción & Inmobiliaria", active: 96, mrr: 44970, arpu: 468 },
      { label: "Tecnología & Software", active: 66, mrr: 40399, arpu: 612 },
      { label: "Distribución & Retail", active: 58, mrr: 39227, arpu: 676 },
    ],
    partners: [
      { name: "Santander", clients: 155, mrr: 116940 },
      { name: "Cobee", clients: 33, mrr: 50125 },
      { name: "Wolters Kluwer", clients: 29, mrr: 39925 },
      { name: "Nailted", clients: 9, mrr: 28791 },
    ],
    strategy: {
      leadChannel: "Multi-channel orchestration",
      leadChannelDetail: "No single channel dominates (Partners 34%, OB 24%, IB 20%). All channels perform well — the opportunity is in orchestration and sequencing, not choosing one.",
      partnerPlay: "Route M/L/XL through partners first",
      partnerDetail: "Partner ARPU (€1,128) is 2.3x Inbound ARPU (€492). Every M+ deal routed to partners is worth more. Cobee (33 clients) and Wolters Kluwer (29) are the growth engines beyond Santander.",
      sizeFocus: "S+M volume, push M conversion",
      sizeDetail: "S+M = 68% of MRR. The M segment (€1,070 ARPU) is 3x the S segment (€361). Shifting 10% of pipeline from S to M = significant ARPU uplift without changing total volume.",
      arpuAssessment: "Below national average (€676 vs €729). Driven by heavy S-segment mix. Upselling M clients and pushing L deals would close the gap.",
      conversionAssessment: "D2W of 84.7% is 5.5pp above national — best among top 5 CCAAs. The funnel works. Increase top-of-funnel volume, especially outbound (87% D2W).",
    },
    keyInsights: [
      "Highest volume market: 1,951 active clients generating €1.3M MRR (27.7% of Spain total)",
      "Best D2W among large CCAAs (84.7%) — funnel is well-oiled, add volume",
      "Outbound D2W = 87% — highest of any channel. SDR investment here pays off directly",
      "Telefónica ARPU €1,142 but only 25 active clients — massive per-deal value, tiny footprint",
      "17,042 untapped TAM companies (89.7%) — still enormous headroom despite being #1",
    ],
    openQuestions: [
      "Why is ARPU below national despite being the largest market? Is it size mix or pricing?",
      "Can we scale Cobee/Wolters Kluwer partnerships to Santander-level volumes?",
      "Should we dedicate SDR capacity here given the 87% outbound D2W?",
      "Telefónica has 59 pipeline / 25 active — is the deal source drying up or just scaling slowly?",
    ],
  },
  {
    ccaa: "Comunidad de Madrid",
    code: "MD",
    archetype: "multi-channel",
    tam: 17308,
    hubspot: 7083,
    active: 1467,
    won: 1991,
    demos: 2476,
    mrr: 1176835,
    arpu: 802,
    d2w: 80.4,
    penetration: 8.5,
    mrrPerTam: 68.0,
    sizes: [
      { label: "S (20-50)", pipeline: 4848, active: 922, mrr: 355421, arpu: 385, d2w: 88, mrrShare: 30 },
      { label: "M (51-200)", pipeline: 1105, active: 352, mrr: 392183, arpu: 1114, d2w: 73, mrrShare: 33 },
      { label: "L (201-500)", pipeline: 539, active: 99, mrr: 234794, arpu: 2372, d2w: 58, mrrShare: 20 },
      { label: "XL (500+)", pipeline: 475, active: 61, mrr: 188820, arpu: 3095, d2w: 53, mrrShare: 16 },
    ],
    provenances: [
      { label: "Channel Partners", pipeline: 667, active: 266, mrr: 444328, mrrShare: 38, arpu: 1670, d2w: 74 },
      { label: "Inbound", pipeline: 3046, active: 474, mrr: 291029, mrrShare: 25, arpu: 614, d2w: 82 },
      { label: "Outbound", pipeline: 1784, active: 281, mrr: 202367, mrrShare: 17, arpu: 720, d2w: 77 },
      { label: "Paid", pipeline: 1061, active: 206, mrr: 105680, mrrShare: 9, arpu: 513, d2w: 80 },
      { label: "Santander", pipeline: 177, active: 86, mrr: 81667, mrrShare: 7, arpu: 950, d2w: 69 },
      { label: "Telefónica", pipeline: 91, active: 37, mrr: 28776, mrrShare: 2, arpu: 778, d2w: 59 },
    ],
    industries: [
      { label: "Construcción & Inmobiliaria", active: 83, mrr: 62536, arpu: 753 },
      { label: "Hostelería & Turismo", active: 41, mrr: 55279, arpu: 1348 },
      { label: "Tecnología & Software", active: 68, mrr: 51998, arpu: 765 },
      { label: "Transporte & Logística", active: 28, mrr: 45785, arpu: 1635 },
      { label: "Hostelería & Turismo", active: 69, mrr: 45690, arpu: 662 },
      { label: "Tecnología & Software", active: 89, mrr: 45031, arpu: 506 },
    ],
    partners: [
      { name: "Santander", clients: 82, mrr: 73192 },
      { name: "Wolters Kluwer", clients: 14, mrr: 70223 },
      { name: "Cobee", clients: 30, mrr: 65537 },
      { name: "Telefonica", clients: 36, mrr: 28555 },
    ],
    strategy: {
      leadChannel: "Partner-led with enterprise focus",
      leadChannelDetail: "Partners generate 47% of MRR (including Santander/Telefónica). Partner ARPU is €1,670 — the highest of any channel in any CCAA. Madrid is the enterprise capital of Spain.",
      partnerPlay: "Expand Wolters Kluwer and build new enterprise partners",
      partnerDetail: "Wolters Kluwer delivers €70K MRR with only 14 clients (€5,016 ARPU!). Cobee at €65K/30 clients. The partner network here generates massive deal sizes — recruit more enterprise-tier partners.",
      sizeFocus: "L/XL enterprise, protect M base",
      sizeDetail: "L/XL = 36% of MRR (highest of any CCAA). XL ARPU = €3,095. Madrid is where big deals happen. Dedicate senior AEs and ensure L/XL pipeline never starves.",
      arpuAssessment: "Above national average (€802 vs €729). Driven by strong L/XL mix and premium partner deal sizes. The only top-5 CCAA above national ARPU.",
      conversionAssessment: "D2W at 80.4% is in line with national. L/XL D2W drops to 53-58% — enterprise cycles are harder. Invest in enterprise sales enablement.",
    },
    keyInsights: [
      "Enterprise capital: L/XL = 36% of MRR, XL ARPU €3,095 (highest in Spain)",
      "Wolters Kluwer: 14 clients, €70K MRR — €5,016 per client. The proof that enterprise partners work",
      "Partner ARPU (€1,670) is 2.7x Inbound (€614) — the largest gap in any CCAA",
      "Transport vertical: €1,635 ARPU with 28 clients — highly concentrated, premium sector",
      "15,841 untapped TAM (91.5%) — second largest whitespace in absolute terms",
    ],
    openQuestions: [
      "Can we replicate the Wolters Kluwer model (low volume, ultra-high ARPU) with 2-3 more partners?",
      "Enterprise D2W is 53-58% — are we losing on price, product fit, or sales cycle management?",
      "Telefónica D2W = 59% (worst in Madrid). Is this a handoff problem or lead quality?",
      "Is the €1,348 Leisure & Tourism ARPU driven by hotel chains or travel agencies? Different approach needed.",
    ],
  },
  {
    ccaa: "Andalucía",
    code: "AN",
    archetype: "multi-channel",
    tam: 11678,
    hubspot: 4005,
    active: 644,
    won: 882,
    demos: 1164,
    mrr: 431908,
    arpu: 671,
    d2w: 75.8,
    penetration: 5.5,
    mrrPerTam: 37.0,
    sizes: [
      { label: "S (20-50)", pipeline: 2941, active: 438, mrr: 155379, arpu: 355, d2w: 82, mrrShare: 36 },
      { label: "M (51-200)", pipeline: 527, active: 131, mrr: 157521, arpu: 1202, d2w: 68, mrrShare: 36 },
      { label: "L (201-500)", pipeline: 270, active: 33, mrr: 70603, arpu: 2139, d2w: 49, mrrShare: 16 },
      { label: "XL (500+)", pipeline: 182, active: 29, mrr: 46103, arpu: 1590, d2w: 54, mrrShare: 11 },
    ],
    provenances: [
      { label: "Channel Partners", pipeline: 291, active: 117, mrr: 106078, mrrShare: 25, arpu: 907, d2w: 71 },
      { label: "Inbound", pipeline: 1841, active: 210, mrr: 105689, mrrShare: 24, arpu: 503, d2w: 81 },
      { label: "Outbound", pipeline: 1016, active: 110, mrr: 94659, mrrShare: 22, arpu: 861, d2w: 72 },
      { label: "Paid", pipeline: 606, active: 102, mrr: 49539, mrrShare: 11, arpu: 486, d2w: 70 },
      { label: "Santander", pipeline: 118, active: 47, mrr: 39254, mrrShare: 9, arpu: 835, d2w: 67 },
      { label: "Telefónica", pipeline: 44, active: 30, mrr: 31736, mrrShare: 7, arpu: 1058, d2w: 76 },
    ],
    industries: [
      { label: "Salud", active: 17, mrr: 44655, arpu: 2627 },
      { label: "Hostelería & Turismo", active: 45, mrr: 31463, arpu: 699 },
      { label: "Distribución & Retail", active: 10, mrr: 23349, arpu: 2335 },
      { label: "Construcción & Inmobiliaria", active: 49, mrr: 21448, arpu: 438 },
      { label: "Agroalimentario", active: 19, mrr: 21070, arpu: 1109 },
      { label: "Distribución & Retail", active: 9, mrr: 18679, arpu: 2075 },
    ],
    partners: [
      { name: "Santander", clients: 45, mrr: 38905 },
      { name: "AWS", clients: 2, mrr: 26085 },
      { name: "Telefonica", clients: 26, mrr: 23554 },
      { name: "Cobee", clients: 4, mrr: 8361 },
    ],
    strategy: {
      leadChannel: "Multi-channel with vertical specialization",
      leadChannelDetail: "Balanced across Partners (25%), IB (24%), OB (22%). No channel dominates — but industry verticals show extreme ARPU variance (Healthcare €2,627 vs Construction €438). Go vertical.",
      partnerPlay: "Build local partners — Telefónica outperforms Santander here",
      partnerDetail: "Telefónica ARPU (€1,058) > Santander (€835) — unusual. Telefónica D2W (76%) beats Santander (67%). Invest in Telefónica expansion in Andalucía specifically. Also recruit agro/food partners for the farming vertical.",
      sizeFocus: "M segment is the battleground",
      sizeDetail: "M = 36% of MRR, matching S. But M ARPU (€1,202) is 3.4x S (€355). Every lead moved from S to M pipeline = 3.4x value. L D2W at 49% is the worst among top CCAAs — enterprise deals are dying.",
      arpuAssessment: "Below national (€671 vs €729). Heavy S-segment mix drags it down. Healthcare and Apparel verticals show €2,000+ ARPU — these are the expansion vectors.",
      conversionAssessment: "D2W at 75.8% is 3.4pp below national. L segment D2W = 49% — alarming. Either demo quality for L is poor or AEs aren't equipped for enterprise Andalucía deals.",
    },
    keyInsights: [
      "Third-largest TAM (11,678) but only 5.5% penetration — 2nd largest absolute whitespace (11,034)",
      "Healthcare ARPU (€2,627) is 3.9x national — niche goldmine with only 17 active clients",
      "Telefónica outperforms Santander here: higher ARPU (€1,058 vs €835) and better D2W (76% vs 67%)",
      "L segment D2W = 49% — worst of any top-5 CCAA. Enterprise deals need urgent attention",
      "Farming vertical: 19 active, €1,109 ARPU — Andalucía is Spain's agri-heartland",
    ],
    openQuestions: [
      "What's killing the L-segment D2W (49%)? Is it AE skill, product fit, or competition?",
      "Healthcare at €2,627 ARPU with only 17 clients — is there a partner or vertical sales play?",
      "Can we build a local Andalucían partner (like Galicia's Landín) to replace reliance on national channels?",
      "Farming has enormous potential (Spain's agricultural hub) — is there an agtech partner play?",
    ],
  },
  {
    ccaa: "Comunidad Valenciana",
    code: "VC",
    archetype: "outbound-responsive",
    tam: 8766,
    hubspot: 3068,
    active: 475,
    won: 681,
    demos: 967,
    mrr: 391842,
    arpu: 825,
    d2w: 70.4,
    penetration: 5.4,
    mrrPerTam: 44.7,
    sizes: [
      { label: "S (20-50)", pipeline: 2308, active: 336, mrr: 129709, arpu: 386, d2w: 77, mrrShare: 33 },
      { label: "M (51-200)", pipeline: 415, active: 98, mrr: 166897, arpu: 1703, d2w: 62, mrrShare: 43 },
      { label: "L (201-500)", pipeline: 181, active: 22, mrr: 79884, arpu: 3631, d2w: 48, mrrShare: 20 },
      { label: "XL (500+)", pipeline: 111, active: 9, mrr: 12691, arpu: 1410, d2w: 38, mrrShare: 3 },
    ],
    provenances: [
      { label: "Outbound", pipeline: 868, active: 109, mrr: 134997, mrrShare: 34, arpu: 1239, d2w: 62 },
      { label: "Channel Partners", pipeline: 244, active: 85, mrr: 113192, mrrShare: 29, arpu: 1332, d2w: 61 },
      { label: "Inbound", pipeline: 1356, active: 143, mrr: 65580, mrrShare: 17, arpu: 459, d2w: 76 },
      { label: "Paid", pipeline: 436, active: 63, mrr: 30294, mrrShare: 8, arpu: 481, d2w: 66 },
      { label: "Telefónica", pipeline: 23, active: 13, mrr: 18574, mrrShare: 5, arpu: 1429, d2w: 73 },
      { label: "Santander", pipeline: 52, active: 24, mrr: 17280, mrrShare: 4, arpu: 720, d2w: 65 },
    ],
    industries: [
      { label: "Agroalimentario", active: 6, mrr: 64377, arpu: 10729 },
      { label: "Hostelería & Turismo", active: 19, mrr: 26396, arpu: 1389 },
      { label: "Tecnología & Software", active: 20, mrr: 19550, arpu: 977 },
      { label: "Industria & Manufactura", active: 6, mrr: 16363, arpu: 2727 },
      { label: "Construcción & Inmobiliaria", active: 25, mrr: 15433, arpu: 617 },
      { label: "Distribución & Retail", active: 12, mrr: 13976, arpu: 1165 },
    ],
    partners: [
      { name: "Telefonica", clients: 12, mrr: 18483 },
      { name: "Santander", clients: 24, mrr: 17280 },
      { name: "Laberit", clients: 4, mrr: 16957 },
      { name: "TIM", clients: 1, mrr: 13188 },
    ],
    strategy: {
      leadChannel: "Outbound-first with partner amplification",
      leadChannelDetail: "Outbound = 34% of MRR (highest of any top-5 CCAA). OB ARPU (€1,239) is 2.7x Inbound (€459). This is a market that responds to proactive outreach — invest SDR hours here.",
      partnerPlay: "Use partners for M+ deals, expand Laberit & recruit ceramics/agri partners",
      partnerDetail: "Partner ARPU (€1,332) is strong but D2W is only 61%. Partners source good deals but closing is weak. Need to improve partner-to-AE handoff or co-selling model.",
      sizeFocus: "M segment dominance — €1,703 ARPU",
      sizeDetail: "M = 43% of MRR with €1,703 ARPU (highest M-segment ARPU in Spain). L ARPU at €3,631 is also exceptional. But XL is nearly dead (€12.7K MRR, 38% D2W). Focus M/L, deprioritize XL.",
      arpuAssessment: "Well above national (€825 vs €729). Driven by strong M and L deal sizes. Farming at €10,729 ARPU is an outlier to investigate and potentially scale.",
      conversionAssessment: "D2W at 70.4% is 8.8pp below national — worst of top 5. XL D2W = 38% (catastrophic). Something structural is breaking in the closing process. Urgent fix needed.",
    },
    keyInsights: [
      "Farming ARPU = €10,729 — the single highest vertical ARPU in all of Spain (only 6 clients!)",
      "Outbound-first: OB generates 34% of MRR with €1,239 ARPU — SDR investment pays off 2.7x vs IB",
      "M-segment ARPU (€1,703) is highest in Spain — this is where the mid-market premium lives",
      "D2W problem: 70.4% overall, 38% XL — enterprise conversion is broken. Fix before scaling",
      "Telefónica ARPU €1,429 (highest in any CCAA) — few deals but massive value each",
    ],
    openQuestions: [
      "What is driving the €10,729 Farming ARPU? Are these large agri-cooperatives or tech-forward farms?",
      "Why is D2W so low (70.4%)? Is it AE quality, competitive pressure, or misqualified demos?",
      "XL D2W at 38% — should we stop pursuing XL in Valencia or change the sales process?",
      "Can we build a ceramics/manufacturing partner for the Castellón corridor?",
    ],
  },
  {
    ccaa: "Galicia",
    code: "GA",
    archetype: "partner-led",
    tam: 4431,
    hubspot: 1660,
    active: 343,
    won: 411,
    demos: 530,
    mrr: 325640,
    arpu: 949,
    d2w: 77.5,
    penetration: 7.7,
    mrrPerTam: 73.5,
    sizes: [
      { label: "S (20-50)", pipeline: 1171, active: 222, mrr: 74983, arpu: 338, d2w: 82, mrrShare: 23 },
      { label: "M (51-200)", pipeline: 232, active: 68, mrr: 88419, arpu: 1300, d2w: 70, mrrShare: 27 },
      { label: "L (201-500)", pipeline: 104, active: 24, mrr: 60998, arpu: 2542, d2w: 80, mrrShare: 19 },
      { label: "XL (500+)", pipeline: 121, active: 19, mrr: 100381, arpu: 5283, d2w: 57, mrrShare: 31 },
    ],
    provenances: [
      { label: "Channel Partners", pipeline: 227, active: 128, mrr: 173217, mrrShare: 53, arpu: 1353, d2w: 79 },
      { label: "Outbound", pipeline: 406, active: 55, mrr: 54293, mrrShare: 17, arpu: 987, d2w: 74 },
      { label: "Inbound", pipeline: 711, active: 77, mrr: 38230, mrrShare: 12, arpu: 496, d2w: 80 },
      { label: "Telefónica", pipeline: 17, active: 8, mrr: 27957, mrrShare: 9, arpu: 3495, d2w: 67 },
      { label: "Paid", pipeline: 225, active: 36, mrr: 17469, mrrShare: 5, arpu: 485, d2w: 66 },
      { label: "Santander", pipeline: 44, active: 25, mrr: 13025, mrrShare: 4, arpu: 521, d2w: 77 },
    ],
    industries: [
      { label: "Agroalimentario", active: 12, mrr: 46744, arpu: 3895 },
      { label: "Tecnología & Software", active: 20, mrr: 41187, arpu: 2059 },
      { label: "Hostelería & Turismo", active: 17, mrr: 20226, arpu: 1190 },
      { label: "Hostelería & Turismo", active: 8, mrr: 19141, arpu: 2393 },
      { label: "Educación & Formación", active: 5, mrr: 18953, arpu: 3791 },
      { label: "Construcción & Inmobiliaria", active: 32, mrr: 12117, arpu: 379 },
    ],
    partners: [
      { name: "Landín Informática", clients: 83, mrr: 115336 },
      { name: "Telefonica", clients: 8, mrr: 27957 },
      { name: "Travelperk", clients: 1, mrr: 26201 },
      { name: "Santander", clients: 23, mrr: 11400 },
    ],
    strategy: {
      leadChannel: "Partner-dominated — Landín is the region",
      leadChannelDetail: "Partners = 66% of MRR (highest of any major CCAA). One partner — Landín Informática — generates €115K MRR from 83 clients. This is the single most successful regional partner in Spain.",
      partnerPlay: "Scale Landín and recruit a second local anchor partner",
      partnerDetail: "Landín is 35% of the entire region's MRR. That's extraordinary but also a concentration risk. Find 1-2 more local partners to diversify while maintaining the partner-first model. Also: Travelperk contributed €26K from a single deal.",
      sizeFocus: "XL drives 31% of MRR — enterprise region",
      sizeDetail: "XL = 31% of MRR with €5,283 ARPU (highest in Spain). L D2W = 80% (also best in Spain). Galicia's partner network excels at selling to large enterprises. Don't dilute this with SMB volume plays.",
      arpuAssessment: "30% above national (€949 vs €729). Driven by XL concentration and partner deal quality. Third-highest ARPU in Spain — premium market worth protecting.",
      conversionAssessment: "D2W at 77.5% is slightly below national but L segment D2W = 80% (best in Spain). Enterprise closing is strong. XL at 57% is the only weak spot.",
    },
    keyInsights: [
      "The Landín Effect: 1 partner = €115K MRR (35% of region). The blueprint for regional partner expansion",
      "Highest €/TAM in Spain (€73.5) — per-company revenue extraction is best-in-class",
      "XL ARPU €5,283 — highest in any CCAA. L D2W = 80% — also highest. Enterprise machine.",
      "Food & Beverages ARPU €3,895 — the Galician food industry is a goldmine",
      "Telefónica per-client: €3,495 ARPU (8 clients) — massive deal sizes from corporate partnerships",
    ],
    openQuestions: [
      "How did Landín Informática achieve 83 clients? Can we formalize this playbook for other regions?",
      "Landín concentration risk: what's the plan if they shift priorities or downsize?",
      "Food & Beverages at €3,895 ARPU — are these fish processing plants, wineries, or both?",
      "Can outbound (€987 ARPU, 74% D2W) scale to become a second growth engine alongside partners?",
    ],
  },
  {
    ccaa: "Canarias",
    code: "CN",
    archetype: "outbound-responsive",
    tam: 3940,
    hubspot: 1203,
    active: 237,
    won: 287,
    demos: 341,
    mrr: 158372,
    arpu: 668,
    d2w: 84.2,
    penetration: 6.0,
    mrrPerTam: 40.2,
    sizes: [
      { label: "S (20-50)", pipeline: 842, active: 154, mrr: 51608, arpu: 335, d2w: 87, mrrShare: 33 },
      { label: "M (51-200)", pipeline: 173, active: 49, mrr: 47845, arpu: 976, d2w: 81, mrrShare: 30 },
      { label: "L (201-500)", pipeline: 85, active: 14, mrr: 28267, arpu: 2019, d2w: 65, mrrShare: 18 },
      { label: "XL (500+)", pipeline: 68, active: 13, mrr: 30047, arpu: 2311, d2w: 67, mrrShare: 19 },
    ],
    provenances: [
      { label: "Outbound", pipeline: 345, active: 53, mrr: 43160, mrrShare: 27, arpu: 814, d2w: 95 },
      { label: "Channel Partners", pipeline: 84, active: 40, mrr: 34843, mrrShare: 22, arpu: 871, d2w: 74 },
      { label: "Inbound", pipeline: 511, active: 65, mrr: 26541, mrrShare: 17, arpu: 408, d2w: 82 },
      { label: "Paid", pipeline: 181, active: 30, mrr: 20329, mrrShare: 13, arpu: 678, d2w: 71 },
      { label: "Santander", pipeline: 25, active: 15, mrr: 19343, mrrShare: 12, arpu: 1290, d2w: 91 },
      { label: "Telefónica", pipeline: 24, active: 13, mrr: 9633, mrrShare: 6, arpu: 741, d2w: 67 },
    ],
    industries: [
      { label: "Hostelería & Turismo", active: 25, mrr: 26226, arpu: 1049 },
      { label: "Hostelería & Turismo", active: 12, mrr: 16956, arpu: 1413 },
      { label: "Transporte & Logística", active: 8, mrr: 12598, arpu: 1575 },
      { label: "Agroalimentario", active: 11, mrr: 11749, arpu: 1068 },
      { label: "Hostelería & Turismo", active: 10, mrr: 5489, arpu: 549 },
    ],
    partners: [
      { name: "Santander", clients: 15, mrr: 19343 },
      { name: "Telefonica", clients: 12, mrr: 9097 },
      { name: "Adlanter", clients: 2, mrr: 7430 },
      { name: "V Valley España", clients: 9, mrr: 7087 },
    ],
    strategy: {
      leadChannel: "Outbound excellence — 95% D2W",
      leadChannelDetail: "Outbound D2W = 95% (!). The best outbound conversion in all of Spain. Every demo sourced by outbound in Canarias almost certainly converts. SDR hours here are pure gold.",
      partnerPlay: "Santander + V Valley as anchors, tourism-specific partners needed",
      partnerDetail: "Santander: 15 clients, €1,290 ARPU, 91% D2W. Santander in Canarias is a conversion machine. V Valley has 9 clients — potentially the local tech distributor for the region.",
      sizeFocus: "L/XL = 37% MRR despite small market",
      sizeDetail: "Even in an island economy, L/XL deals are significant. XL ARPU (€2,311) and L (€2,019) show enterprise-grade deals are closing. Focus on hospitality chains and transport for L+ deals.",
      arpuAssessment: "Below national (€668 vs €729). Tourism and hospitality keep ARPU moderate — but Santander deals at €1,290 show premium is achievable through the right channel.",
      conversionAssessment: "D2W at 84.2% is 5pp above national. Outbound at 95% D2W and Santander at 91% are extraordinary. Maximize volume through these two channels.",
    },
    keyInsights: [
      "95% outbound D2W — the best in Spain. Every SDR hour in Canarias is the most efficient investment",
      "Santander D2W = 91% at €1,290 ARPU — the perfect partner-channel combination",
      "Tourism-dominated economy: Hospitality + Leisure = 27% of MRR. Need specialized tourism expertise",
      "Transport ARPU €1,575 (8 clients) — logistics/shipping in an island economy commands premium pricing",
      "3,703 untapped TAM — small but with best-in-class conversion, high-ROI expansion market",
    ],
    openQuestions: [
      "Why is outbound D2W 95%? Is it lead quality, market receptiveness, or a specific SDR?",
      "Should we assign a dedicated SDR for Canarias given the conversion rates?",
      "Is V Valley España the right local partner or do we need a Canarias-native IT reseller?",
      "Tourism seasonality — should outbound campaigns be timed around hotel hiring/expansion cycles?",
    ],
  },
  {
    ccaa: "País Vasco",
    code: "PV",
    archetype: "outbound-responsive",
    tam: 5297,
    hubspot: 1440,
    active: 233,
    won: 304,
    demos: 402,
    mrr: 147088,
    arpu: 631,
    d2w: 75.6,
    penetration: 4.4,
    mrrPerTam: 27.8,
    sizes: [
      { label: "S (20-50)", pipeline: 1021, active: 149, mrr: 48134, arpu: 323, d2w: 81, mrrShare: 33 },
      { label: "M (51-200)", pipeline: 195, active: 47, mrr: 58935, arpu: 1254, d2w: 72, mrrShare: 40 },
      { label: "L (201-500)", pipeline: 110, active: 19, mrr: 26019, arpu: 1369, d2w: 62, mrrShare: 18 },
      { label: "XL (500+)", pipeline: 94, active: 9, mrr: 13197, arpu: 1466, d2w: 43, mrrShare: 9 },
    ],
    provenances: [
      { label: "Outbound", pipeline: 357, active: 53, mrr: 43827, mrrShare: 30, arpu: 827, d2w: 75 },
      { label: "Channel Partners", pipeline: 124, active: 51, mrr: 34372, mrrShare: 23, arpu: 674, d2w: 72 },
      { label: "Inbound", pipeline: 621, active: 52, mrr: 29047, mrrShare: 20, arpu: 559, d2w: 64 },
      { label: "Santander", pipeline: 31, active: 16, mrr: 19234, mrrShare: 13, arpu: 1202, d2w: 76 },
      { label: "Paid", pipeline: 253, active: 44, mrr: 12765, mrrShare: 9, arpu: 290, d2w: 90 },
      { label: "Telefónica", pipeline: 16, active: 5, mrr: 6004, mrrShare: 4, arpu: 1201, d2w: 43 },
    ],
    industries: [
      { label: "Salud", active: 8, mrr: 11469, arpu: 1434 },
      { label: "Hostelería & Turismo", active: 6, mrr: 11236, arpu: 1873 },
      { label: "Industria & Manufactura", active: 11, mrr: 9378, arpu: 853 },
      { label: "Distribución & Retail", active: 6, mrr: 9047, arpu: 1508 },
      { label: "Tecnología & Software", active: 11, mrr: 8690, arpu: 790 },
      { label: "Hostelería & Turismo", active: 9, mrr: 7049, arpu: 783 },
    ],
    partners: [
      { name: "Santander", clients: 16, mrr: 19234 },
      { name: "Telefonica", clients: 3, mrr: 4808 },
      { name: "PKF-Attest", clients: 5, mrr: 3567 },
    ],
    strategy: {
      leadChannel: "Outbound + Santander for M+ deals",
      leadChannelDetail: "OB = 30% MRR, Santander ARPU = €1,202. Inbound D2W is only 64% — the worst inbound conversion in any major CCAA. Outbound and Santander are the proven paths.",
      partnerPlay: "Recruit Basque-local partners — PKF-Attest is a start",
      partnerDetail: "Partner network is thin. PKF-Attest has 5 clients but it's the only local partner of note. The Basque business ecosystem is distinct (cooperatives, industrial clusters) — need a partner who speaks that language.",
      sizeFocus: "M segment = 40% MRR, the primary battleground",
      sizeDetail: "M ARPU (€1,254) is solid but below Valencia's €1,703. XL D2W at 43% means enterprise is very hard here. Focus on growing M volume and pushing L conversion (62% D2W).",
      arpuAssessment: "Below national (€631 vs €729). Paid ARPU of €290 is dragging the mix — Paid leads in País Vasco are low-quality. Could be a targeting issue.",
      conversionAssessment: "D2W at 75.6% is below national. Inbound D2W = 64% — structural issue with inbound lead quality. Paid D2W = 90% but €290 ARPU — high volume, low value.",
    },
    keyInsights: [
      "Largest relative whitespace: 5,297 TAM but only 4.4% penetration — lowest €/TAM (€27.8) among major CCAAs",
      "Inbound D2W = 64% — worst in Spain. Inbound leads here aren't converting. Need to investigate",
      "Paid D2W = 90% but ARPU = €290 — buying micro-deals. Rethink paid targeting for País Vasco",
      "Industrial Automation (11 active, €853 ARPU) — aligns with Basque industrial tradition",
      "Santander ARPU €1,202 — the reliable premium channel here. Expand Santander coverage.",
    ],
    openQuestions: [
      "Why is inbound D2W so low (64%)? Are wrong-fit leads entering the funnel or is it a demo quality issue?",
      "Paid generates 90% D2W at €290 ARPU — is it worth it? Should paid budget shift to other CCAAs?",
      "Is the Basque cooperative model (Mondragon-style) a unique sales angle we're not leveraging?",
      "Can PKF-Attest or a similar firm scale to become the Landín equivalent for País Vasco?",
    ],
  },
  {
    ccaa: "Castilla y León",
    code: "CL",
    archetype: "partner-led",
    tam: 4796,
    hubspot: 2368,
    active: 224,
    won: 297,
    demos: 398,
    mrr: 135809,
    arpu: 606,
    d2w: 74.6,
    penetration: 4.7,
    mrrPerTam: 28.3,
    sizes: [
      { label: "S (20-50)", pipeline: 1965, active: 151, mrr: 50877, arpu: 337, d2w: 78, mrrShare: 37 },
      { label: "M (51-200)", pipeline: 194, active: 50, mrr: 68152, arpu: 1363, d2w: 84, mrrShare: 50 },
      { label: "L (201-500)", pipeline: 99, active: 9, mrr: 8436, arpu: 937, d2w: 38, mrrShare: 6 },
      { label: "XL (500+)", pipeline: 77, active: 8, mrr: 7587, arpu: 948, d2w: 44, mrrShare: 6 },
    ],
    provenances: [
      { label: "Channel Partners", pipeline: 107, active: 49, mrr: 52643, mrrShare: 39, arpu: 1074, d2w: 89 },
      { label: "Outbound", pipeline: 658, active: 47, mrr: 33065, mrrShare: 24, arpu: 704, d2w: 74 },
      { label: "Santander", pipeline: 59, active: 33, mrr: 20050, mrrShare: 15, arpu: 608, d2w: 69 },
      { label: "Inbound", pipeline: 1313, active: 48, mrr: 14692, mrrShare: 11, arpu: 306, d2w: 64 },
      { label: "Paid", pipeline: 182, active: 34, mrr: 12789, mrrShare: 9, arpu: 376, d2w: 79 },
      { label: "Telefónica", pipeline: 13, active: 2, mrr: 1105, mrrShare: 1, arpu: 553, d2w: 42 },
    ],
    industries: [
      { label: "Agroalimentario", active: 10, mrr: 19662, arpu: 1966 },
      { label: "Educación & Formación", active: 7, mrr: 18281, arpu: 2612 },
      { label: "Agroalimentario", active: 11, mrr: 8839, arpu: 804 },
      { label: "Industria & Manufactura", active: 6, mrr: 7661, arpu: 1277 },
      { label: "Distribución & Retail", active: 10, mrr: 6831, arpu: 683 },
    ],
    partners: [
      { name: "Santander", clients: 32, mrr: 19780 },
      { name: "Freenow", clients: 1, mrr: 17240 },
      { name: "Wolters Kluwer", clients: 3, mrr: 6004 },
      { name: "Microsoft", clients: 1, mrr: 5853 },
    ],
    strategy: {
      leadChannel: "Partner-first with Santander as anchor",
      leadChannelDetail: "Partners = 54% MRR with 89% D2W — the highest partner D2W in Spain. Partners close here better than anywhere else. Inbound ARPU (€306) is the lowest in Spain — inbound doesn't work well in this dispersed region.",
      partnerPlay: "Scale Santander (32 clients), add local IT partners",
      partnerDetail: "Santander is the regional anchor (32 clients). Freenow generated €17K from 1 deal — outlier but shows enterprise interest exists. Need local IT distributors for the region's dispersed geography.",
      sizeFocus: "M segment = 50% MRR, highest M-dependence in Spain",
      sizeDetail: "M segment produces half the MRR with 84% D2W (best M-segment D2W). L/XL is essentially dead (6% MRR each, 38-44% D2W). This is a mid-market region — don't chase enterprise.",
      arpuAssessment: "Below national (€606 vs €729). Inbound ARPU of €306 drags the average hard. Partner (€1,074) and OB (€704) are closer to national.",
      conversionAssessment: "Partner D2W = 89% (best in Spain). But Inbound D2W = 64% and L D2W = 38%. The partner channel compensates for everything else.",
    },
    keyInsights: [
      "Partner D2W = 89% — highest in all of Spain. Partners are the only channel that truly works here",
      "M segment: 84% D2W, €1,363 ARPU — the sweet spot. Don't go above or below",
      "Inbound ARPU = €306, D2W = 64% — worst inbound performance in Spain. Possible to deprioritize",
      "Education vertical: €2,612 ARPU (7 clients) — universities and schools in the region are high-value",
      "Food & Beverages: €1,966 ARPU (10 clients) — Castilla y León's wine/food tradition is premium",
    ],
    openQuestions: [
      "Should we reduce inbound investment here and redirect to regions with better inbound conversion?",
      "Why are L/XL D2W rates so low (38-44%)? Is the region too dispersed for enterprise sales?",
      "Can we find a local IT partner similar to Galicia's Landín for the CyL market?",
      "Is the Education vertical defensible? Are these public universities or private schools?",
    ],
  },
  {
    ccaa: "Región de Murcia",
    code: "MC",
    archetype: "partner-led",
    tam: 2752,
    hubspot: 732,
    active: 134,
    won: 177,
    demos: 277,
    mrr: 121681,
    arpu: 908,
    d2w: 63.9,
    penetration: 4.9,
    mrrPerTam: 44.2,
    sizes: [
      { label: "S (20-50)", pipeline: 513, active: 83, mrr: 38257, arpu: 461, d2w: 70, mrrShare: 31 },
      { label: "M (51-200)", pipeline: 116, active: 32, mrr: 31082, arpu: 971, d2w: 59, mrrShare: 26 },
      { label: "L (201-500)", pipeline: 56, active: 11, mrr: 39760, arpu: 3615, d2w: 57, mrrShare: 33 },
      { label: "XL (500+)", pipeline: 37, active: 7, mrr: 12561, arpu: 1794, d2w: 40, mrrShare: 10 },
    ],
    provenances: [
      { label: "Channel Partners", pipeline: 104, active: 41, mrr: 54920, mrrShare: 45, arpu: 1340, d2w: 61 },
      { label: "Outbound", pipeline: 182, active: 24, mrr: 31220, mrrShare: 26, arpu: 1301, d2w: 63 },
      { label: "Paid", pipeline: 127, active: 22, mrr: 17778, mrrShare: 15, arpu: 808, d2w: 60 },
      { label: "Inbound", pipeline: 284, active: 32, mrr: 13113, mrrShare: 11, arpu: 410, d2w: 63 },
      { label: "Santander", pipeline: 14, active: 5, mrr: 1887, mrrShare: 2, arpu: 377, d2w: 69 },
      { label: "Telefónica", pipeline: 7, active: 3, mrr: 1151, mrrShare: 1, arpu: 384, d2w: 67 },
    ],
    industries: [
      { label: "Agroalimentario", active: 4, mrr: 12802, arpu: 3200 },
      { label: "Tecnología & Software", active: 5, mrr: 9301, arpu: 1860 },
      { label: "Industria & Manufactura", active: 8, mrr: 7014, arpu: 877 },
      { label: "Hostelería & Turismo", active: 4, mrr: 6268, arpu: 1567 },
      { label: "Agroalimentario", active: 6, mrr: 5791, arpu: 965 },
    ],
    partners: [
      { name: "Inforges", clients: 16, mrr: 25766 },
      { name: "PKF-Attest", clients: 1, mrr: 4092 },
      { name: "A3Satel", clients: 1, mrr: 3255 },
    ],
    strategy: {
      leadChannel: "Partner-led — Inforges is the anchor",
      leadChannelDetail: "Partners = 48% of MRR. Inforges dominates (16 clients, €25.8K MRR). Like Galicia's Landín, a single local partner drives the region. Outbound is the #2 channel (26% MRR, €1,301 ARPU).",
      partnerPlay: "Scale Inforges, urgently fix D2W across all channels",
      partnerDetail: "Inforges is strong but partner D2W = 61% — far below national. The partner sources good deals but closing is underperforming. May need co-selling support or AE quality improvement.",
      sizeFocus: "L segment = 33% MRR at €3,615 ARPU",
      sizeDetail: "L is the MRR driver (33%) with the highest L-segment ARPU in Spain (€3,615). But D2W across all sizes is 57-70% — conversion is the bottleneck, not pipeline.",
      arpuAssessment: "24% above national (€908 vs €729). Driven by L-segment concentration and farming/software verticals. Premium market — but conversion needs to match.",
      conversionAssessment: "Worst D2W in Spain (63.9%). No channel exceeds 69%. This is a systemic issue — not channel-specific. Could be AE coverage, demo quality, or market-specific objections.",
    },
    keyInsights: [
      "Worst D2W in Spain (63.9%) — the single most important thing to fix. Every pp improvement = significant MRR",
      "L-segment ARPU €3,615 — highest in Spain for L. Big deals exist but aren't closing efficiently",
      "Inforges = Murcia's Landín (16 clients) — local partner dominance pattern repeats",
      "Farming ARPU €3,200 (4 clients) — Murcia's agricultural sector (lemon/produce) is a premium target",
      "Outbound ARPU €1,301 — 2nd best OB ARPU after Valencia. High value per outbound touch",
    ],
    openQuestions: [
      "Why is D2W 63.9% across ALL channels? Is there a specific AE, product gap, or competitive dynamic?",
      "Is Murcia assigned enough AE capacity? Low D2W + high ARPU suggests deals are worth fighting for",
      "Can Inforges scale to 30+ clients? What's their current capacity and motivation?",
      "Agricultural sector targeting: citrus industry, food processing — is there a specialized partner?",
    ],
  },
  {
    ccaa: "Aragón",
    code: "AR",
    archetype: "partner-led",
    tam: 2947,
    hubspot: 817,
    active: 169,
    won: 204,
    demos: 286,
    mrr: 116564,
    arpu: 690,
    d2w: 71.3,
    penetration: 5.7,
    mrrPerTam: 39.6,
    sizes: [
      { label: "S (20-50)", pipeline: 592, active: 111, mrr: 44397, arpu: 400, d2w: 79, mrrShare: 38 },
      { label: "M (51-200)", pipeline: 116, active: 38, mrr: 44423, arpu: 1169, d2w: 66, mrrShare: 38 },
      { label: "L (201-500)", pipeline: 56, active: 12, mrr: 16884, arpu: 1407, d2w: 46, mrrShare: 14 },
      { label: "XL (500+)", pipeline: 39, active: 6, mrr: 10486, arpu: 1748, d2w: 44, mrrShare: 9 },
    ],
    provenances: [
      { label: "Channel Partners", pipeline: 118, active: 52, mrr: 42812, mrrShare: 37, arpu: 823, d2w: 69 },
      { label: "Outbound", pipeline: 192, active: 32, mrr: 25428, mrrShare: 22, arpu: 795, d2w: 77 },
      { label: "Inbound", pipeline: 337, active: 41, mrr: 18046, mrrShare: 15, arpu: 440, d2w: 71 },
      { label: "Paid", pipeline: 117, active: 20, mrr: 13744, mrrShare: 12, arpu: 687, d2w: 76 },
      { label: "Telefónica", pipeline: 12, active: 7, mrr: 8958, mrrShare: 8, arpu: 1280, d2w: 70 },
      { label: "Santander", pipeline: 26, active: 12, mrr: 5613, mrrShare: 5, arpu: 468, d2w: 58 },
    ],
    industries: [
      { label: "Construcción & Inmobiliaria", active: 11, mrr: 13803, arpu: 1255 },
      { label: "Industria & Manufactura", active: 13, mrr: 8591, arpu: 661 },
      { label: "Agroalimentario", active: 8, mrr: 6926, arpu: 866 },
      { label: "Industria & Manufactura", active: 8, mrr: 6360, arpu: 795 },
      { label: "Tecnología & Software", active: 9, mrr: 5610, arpu: 623 },
    ],
    partners: [
      { name: "Ayanet Recursos Humanos", clients: 23, mrr: 16148 },
      { name: "Telefonica", clients: 7, mrr: 8958 },
      { name: "Wolters Kluwer", clients: 2, mrr: 8951 },
      { name: "Santander", clients: 12, mrr: 5613 },
    ],
    strategy: {
      leadChannel: "Partner-led — Ayanet is the local anchor",
      leadChannelDetail: "Partners = 49% MRR. Ayanet Recursos Humanos (23 clients, €16K) is the local leader. Outbound supplements well (22%, €795 ARPU). Balanced secondary channels.",
      partnerPlay: "Scale Ayanet, connect to automotive/logistics Zaragoza cluster",
      partnerDetail: "Ayanet is an HR consultancy — perfect partner type for Factorial. Telefónica delivers €1,280 ARPU from 7 clients. Wolters Kluwer at €8.9K from just 2 clients shows enterprise appetite.",
      sizeFocus: "S and M evenly split at 38% MRR each",
      sizeDetail: "Balanced S/M mix. L/XL D2W at 44-46% is poor — enterprise is a stretch. Strengthen M conversion (currently 66%) to maximize return.",
      arpuAssessment: "Slightly below national (€690 vs €729). S ARPU (€400) is above national S average — good S-segment deal sizes. Push to grow M share.",
      conversionAssessment: "D2W at 71.3% is weak. Partner D2W = 69% — below expectations. Outbound at 77% is the best-converting channel.",
    },
    keyInsights: [
      "Ayanet Recursos Humanos: HR consultancy as partner — natural fit for Factorial's product. Model to replicate.",
      "Construction ARPU €1,255 (11 clients) — Zaragoza's logistics/industrial hub drives premium construction deals",
      "Outbound D2W (77%) beats Partners (69%) — unusual. May indicate partner training gaps",
      "Telefónica: €1,280 ARPU from 7 clients — consistent premium channel across Aragón",
      "2,778 untapped TAM — mid-sized opportunity with balanced channel mix",
    ],
    openQuestions: [
      "Can we recruit more HR consultancies as partners using the Ayanet playbook?",
      "Outbound converts better than partners (77% vs 69%) — should partners be supported with co-selling?",
      "Is the Zaragoza logistics corridor (Amazon hub, Opel factory) a targetable cluster?",
      "Santander D2W = 58% — lowest in Aragón. Is the Santander team deprioritizing the region?",
    ],
  },
  {
    ccaa: "Castilla-La Mancha",
    code: "CM",
    archetype: "partner-led",
    tam: 4237,
    hubspot: 1007,
    active: 189,
    won: 272,
    demos: 334,
    mrr: 108026,
    arpu: 572,
    d2w: 81.4,
    penetration: 4.5,
    mrrPerTam: 25.5,
    sizes: [
      { label: "S (20-50)", pipeline: 711, active: 117, mrr: 43036, arpu: 368, d2w: 85, mrrShare: 40 },
      { label: "M (51-200)", pipeline: 150, active: 45, mrr: 36835, arpu: 819, d2w: 74, mrrShare: 34 },
      { label: "L (201-500)", pipeline: 68, active: 11, mrr: 16649, arpu: 1514, d2w: 62, mrrShare: 15 },
      { label: "XL (500+)", pipeline: 49, active: 9, mrr: 10458, arpu: 1162, d2w: 69, mrrShare: 10 },
    ],
    provenances: [
      { label: "Channel Partners", pipeline: 87, active: 44, mrr: 27220, mrrShare: 25, arpu: 619, d2w: 80 },
      { label: "Outbound", pipeline: 214, active: 33, mrr: 26719, mrrShare: 25, arpu: 810, d2w: 81 },
      { label: "Inbound", pipeline: 452, active: 48, mrr: 19169, mrrShare: 18, arpu: 399, d2w: 81 },
      { label: "Santander", pipeline: 33, active: 18, mrr: 15209, mrrShare: 14, arpu: 845, d2w: 82 },
      { label: "Telefónica", pipeline: 17, active: 9, mrr: 10260, mrrShare: 9, arpu: 1140, d2w: 67 },
      { label: "Paid", pipeline: 182, active: 25, mrr: 8052, mrrShare: 7, arpu: 322, d2w: 76 },
    ],
    industries: [
      { label: "Construcción & Inmobiliaria", active: 20, mrr: 8667, arpu: 433 },
      { label: "Industria & Manufactura", active: 5, mrr: 7086, arpu: 1417 },
      { label: "Agroalimentario", active: 4, mrr: 7084, arpu: 1771 },
      { label: "Industria & Manufactura", active: 13, mrr: 6774, arpu: 521 },
      { label: "Agroalimentario", active: 12, mrr: 6662, arpu: 555 },
    ],
    partners: [
      { name: "Santander", clients: 18, mrr: 15209 },
      { name: "Telefonica", clients: 8, mrr: 9549 },
      { name: "Cobee", clients: 2, mrr: 4530 },
      { name: "Imedia Comunicacion", clients: 5, mrr: 3322 },
    ],
    strategy: {
      leadChannel: "Balanced — partners + outbound + Santander each ~25%",
      leadChannelDetail: "Unusual balance: Partners, OB, and Santander each contribute ~25% MRR. Telefónica adds 9% at €1,140 ARPU. All channels work at similar D2W (80-82%). A well-functioning multi-source market.",
      partnerPlay: "Santander is the de facto lead partner; build local alternatives",
      partnerDetail: "Santander (18 clients, €845 ARPU, 82% D2W) outperforms the Channel Partners bucket in reliability. Telefónica at €1,140 ARPU adds premium. No strong local partner exists — opportunity for recruitment.",
      sizeFocus: "S+M = 74% MRR — SMB region",
      sizeDetail: "S (40%) + M (34%) dominate. ARPU is the lowest among mid-sized CCAAs (€572). Need to push M share up and increase cross-sell in S base.",
      arpuAssessment: "22% below national (€572 vs €729). M ARPU (€819) is also below typical. The region pays less — could be a product fit issue or underselling.",
      conversionAssessment: "D2W at 81.4% is above national. Good conversion — the problem is deal size, not volume. Higher D2W means every lead that enters the funnel has a good shot at converting.",
    },
    keyInsights: [
      "Good D2W (81.4%) but lowest ARPU (€572) — the funnel converts but we're under-monetizing",
      "Automotive (€1,417 ARPU) and Farming (€1,771) are premium pockets in an otherwise low-ARPU region",
      "Santander D2W = 82% — their best performance in any CCAA. Lean into this.",
      "Telefónica ARPU €1,140 — significant premium over other channels. Expand Telefónica coverage here.",
      "4,048 untapped TAM at 95.5% — large whitespace in a region with proven conversion rates",
    ],
    openQuestions: [
      "Why is ARPU so low? Is it product editions, missing addons, or smaller companies in the pipeline?",
      "Can we upsell the 117 active S-segment clients to higher plans?",
      "Should we recruit a local CLM partner or is Santander/Telefónica sufficient?",
      "Automotive — is this the Puertollano/Ciudad Real industrial cluster? Targetable with OB campaign.",
    ],
  },
  {
    ccaa: "Islas Baleares",
    code: "IB",
    archetype: "multi-channel",
    tam: 2089,
    hubspot: 813,
    active: 165,
    won: 225,
    demos: 263,
    mrr: 97691,
    arpu: 592,
    d2w: 85.6,
    penetration: 7.9,
    mrrPerTam: 46.8,
    sizes: [
      { label: "S (20-50)", pipeline: 581, active: 118, mrr: 44552, arpu: 378, d2w: 90, mrrShare: 46 },
      { label: "M (51-200)", pipeline: 114, active: 28, mrr: 30068, arpu: 1074, d2w: 84, mrrShare: 31 },
      { label: "L (201-500)", pipeline: 64, active: 7, mrr: 14361, arpu: 2052, d2w: 55, mrrShare: 15 },
      { label: "XL (500+)", pipeline: 35, active: 4, mrr: 6421, arpu: 1605, d2w: 33, mrrShare: 7 },
    ],
    provenances: [
      { label: "Channel Partners", pipeline: 58, active: 28, mrr: 24244, mrrShare: 25, arpu: 866, d2w: 82 },
      { label: "Inbound", pipeline: 370, active: 58, mrr: 23447, mrrShare: 24, arpu: 404, d2w: 87 },
      { label: "Outbound", pipeline: 209, active: 32, mrr: 23191, mrrShare: 24, arpu: 725, d2w: 84 },
      { label: "Paid", pipeline: 143, active: 29, mrr: 18171, mrrShare: 19, arpu: 627, d2w: 78 },
      { label: "Santander", pipeline: 11, active: 6, mrr: 3670, mrrShare: 4, arpu: 612, d2w: 67 },
      { label: "Telefónica", pipeline: 6, active: 3, mrr: 1924, mrrShare: 2, arpu: 641, d2w: 50 },
    ],
    industries: [
      { label: "Hostelería & Turismo", active: 39, mrr: 31804, arpu: 815 },
      { label: "Transporte & Logística", active: 5, mrr: 9035, arpu: 1807 },
      { label: "Hostelería & Turismo", active: 7, mrr: 7246, arpu: 1035 },
      { label: "Construcción & Inmobiliaria", active: 13, mrr: 4971, arpu: 382 },
    ],
    partners: [
      { name: "HRider", clients: 2, mrr: 5630 },
      { name: "Santander", clients: 5, mrr: 3539 },
      { name: "Global4", clients: 3, mrr: 2860 },
    ],
    strategy: {
      leadChannel: "Balanced multi-channel — everything converts well",
      leadChannelDetail: "Partners, IB, OB each ~24-25% of MRR. Even Paid delivers 19%. D2W is high across all channels (78-87%). Small market but every channel works — just add volume.",
      partnerPlay: "Tourism-specialized partners needed",
      partnerDetail: "No strong local partner (HRider has 2 clients, Santander 5). Hospitality = 33% of MRR. Need a tourism/hospitality consultancy as anchor partner for the islands.",
      sizeFocus: "S-dominated (46% MRR) — push M for ARPU lift",
      sizeDetail: "S = 46% at €378 ARPU, M = 31% at €1,074. S D2W = 90% (best S conversion in Spain). Volume is easy — challenge is moving the mix upmarket.",
      arpuAssessment: "Below national (€592 vs €729). S-segment dominance + tourism-driven small businesses pull ARPU down. Transport at €1,807 shows premium exists.",
      conversionAssessment: "D2W at 85.6% — 2nd highest in Spain. S D2W = 90%. Conversion isn't the issue — pipeline volume and deal size are.",
    },
    keyInsights: [
      "Second-highest D2W in Spain (85.6%), S D2W = 90% — practically every demo converts",
      "Hospitality = 33% of MRR (39 clients) — the most tourism-dependent CCAA",
      "Above-average penetration (7.9%) for a small TAM — already relatively well-covered",
      "Paid channel works well here (19% MRR, €627 ARPU) — unusual; tourism businesses search online",
      "Only 1,924 untapped TAM — limited absolute headroom, optimize per-client value",
    ],
    openQuestions: [
      "With 7.9% penetration, how much more can we grow? Is 15% penetration realistic for Baleares?",
      "Can we recruit a Balearic hospitality consultancy or hotel management firm as partner?",
      "Is there seasonal buying pattern with tourism? Should campaigns align with pre-season?",
      "Transport ARPU €1,807 — ferry/shipping companies? Worth a targeted OB campaign?",
    ],
  },
  {
    ccaa: "Extremadura",
    code: "EX",
    archetype: "outbound-responsive",
    tam: 1790,
    hubspot: 875,
    active: 107,
    won: 153,
    demos: 184,
    mrr: 89617,
    arpu: 838,
    d2w: 83.2,
    penetration: 6.0,
    mrrPerTam: 50.1,
    sizes: [
      { label: "S (20-50)", pipeline: 607, active: 61, mrr: 22400, arpu: 367, d2w: 87, mrrShare: 25 },
      { label: "M (51-200)", pipeline: 108, active: 20, mrr: 29957, arpu: 1498, d2w: 72, mrrShare: 33 },
      { label: "L (201-500)", pipeline: 72, active: 11, mrr: 25364, arpu: 2306, d2w: 68, mrrShare: 28 },
      { label: "XL (500+)", pipeline: 66, active: 10, mrr: 11082, arpu: 1108, d2w: 69, mrrShare: 12 },
    ],
    provenances: [
      { label: "Outbound", pipeline: 202, active: 17, mrr: 23059, mrrShare: 26, arpu: 1356, d2w: 96 },
      { label: "Channel Partners", pipeline: 52, active: 18, mrr: 22143, mrrShare: 25, arpu: 1230, d2w: 77 },
      { label: "Inbound", pipeline: 449, active: 31, mrr: 17046, mrrShare: 19, arpu: 550, d2w: 77 },
      { label: "Paid", pipeline: 136, active: 22, mrr: 8778, mrrShare: 10, arpu: 399, d2w: 72 },
      { label: "Telefónica", pipeline: 5, active: 3, mrr: 5896, mrrShare: 7, arpu: 1965, d2w: 80 },
      { label: "Santander", pipeline: 11, active: 6, mrr: 3934, mrrShare: 4, arpu: 656, d2w: 88 },
    ],
    industries: [
      { label: "Energía & Medioambiente", active: 3, mrr: 8468, arpu: 2823 },
      { label: "Hostelería & Turismo", active: 2, mrr: 8200, arpu: 4100 },
      { label: "Educación & Formación", active: 1, mrr: 7463, arpu: 7463 },
      { label: "Servicios Profesionales", active: 7, mrr: 6577, arpu: 940 },
      { label: "Hostelería & Turismo", active: 1, mrr: 6498, arpu: 6498 },
    ],
    partners: [
      { name: "Cobee", clients: 2, mrr: 11554 },
      { name: "Telefonica", clients: 3, mrr: 5896 },
      { name: "wellhub", clients: 2, mrr: 5216 },
      { name: "Santander", clients: 6, mrr: 3934 },
    ],
    strategy: {
      leadChannel: "Outbound gold — 96% D2W",
      leadChannelDetail: "Outbound D2W = 96% at €1,356 ARPU. Second-highest OB D2W in Spain (after Canarias). Outbound in Extremadura is essentially guaranteed conversion at premium deal sizes.",
      partnerPlay: "Cobee as anchor, recruit local partners for dispersed geography",
      partnerDetail: "Cobee (€11.5K, 2 clients) and Telefónica (€5.9K, 3 clients, €1,965 ARPU!) are the main partners. No local IT partner — the region's spread-out geography (Cáceres/Badajoz) needs local presence.",
      sizeFocus: "M/L balanced — enterprise-grade for a small CCAA",
      sizeDetail: "M=33%, L=28% of MRR. L ARPU (€2,306) and M ARPU (€1,498) are both strong. Even S D2W = 87%. A market that over-delivers for its size.",
      arpuAssessment: "15% above national (€838 vs €729). Strong M/L mix drives premium. Telefónica ARPU at €1,965 is remarkable.",
      conversionAssessment: "D2W at 83.2% is above national. OB at 96% is extraordinary. Conversion is a strength — investment should focus on increasing pipeline volume.",
    },
    keyInsights: [
      "Outbound D2W = 96% — tied with Canarias for best OB conversion in Spain",
      "Telefónica ARPU €1,965 — highest Telefónica ARPU in any CCAA. Only 3 clients — massive expansion opportunity",
      "€/TAM = €50.1 — 5th highest in Spain. Efficiently monetizing a small market",
      "M/L = 61% of MRR in a region with only 1,790 TAM — punching above its weight in deal sizes",
      "1,683 untapped TAM — small but with 96% OB D2W, every outbound touch is nearly guaranteed",
    ],
    openQuestions: [
      "With 96% OB D2W, is SDR allocation to Extremadura proportional? Could be under-resourced",
      "Telefónica €1,965 ARPU from 3 clients — can Telefónica scale to 10-15 deals here?",
      "Is the dispersed geography (Cáceres/Badajoz/Mérida) limiting partner and AE effectiveness?",
      "Environmental Services at €2,823 ARPU — renewable energy installations? Worth investigating.",
    ],
  },
  {
    ccaa: "Comunidad Foral de Navarra",
    code: "NC",
    archetype: "partner-led",
    tam: 1079,
    hubspot: 314,
    active: 62,
    won: 90,
    demos: 108,
    mrr: 66882,
    arpu: 1079,
    d2w: 83.3,
    penetration: 5.7,
    mrrPerTam: 62.0,
    sizes: [
      { label: "S (20-50)", pipeline: 215, active: 35, mrr: 21431, arpu: 612, d2w: 82, mrrShare: 32 },
      { label: "M (51-200)", pipeline: 56, active: 20, mrr: 29394, arpu: 1470, d2w: 90, mrrShare: 44 },
      { label: "L (201-500)", pipeline: 19, active: 2, mrr: 1830, arpu: 915, d2w: 43, mrrShare: 3 },
      { label: "XL (500+)", pipeline: 16, active: 4, mrr: 14136, arpu: 3534, d2w: null, mrrShare: 21 },
    ],
    provenances: [
      { label: "Channel Partners", pipeline: 30, active: 17, mrr: 28926, mrrShare: 43, arpu: 1702, d2w: 88 },
      { label: "Outbound", pipeline: 86, active: 12, mrr: 19727, mrrShare: 29, arpu: 1644, d2w: 83 },
      { label: "Santander", pipeline: 6, active: 3, mrr: 6305, mrrShare: 9, arpu: 2102, d2w: 80 },
      { label: "Inbound", pipeline: 128, active: 17, mrr: 5137, mrrShare: 8, arpu: 302, d2w: 85 },
      { label: "Paid", pipeline: 48, active: 8, mrr: 3809, mrrShare: 6, arpu: 476, d2w: 61 },
      { label: "Telefónica", pipeline: 4, active: 2, mrr: 2668, mrrShare: 4, arpu: 1334, d2w: null },
    ],
    industries: [
      { label: "Hostelería & Turismo", active: 1, mrr: 9658, arpu: 9658 },
      { label: "Salud", active: 3, mrr: 7844, arpu: 2615 },
      { label: "Transporte & Logística", active: 1, mrr: 6255, arpu: 6255 },
      { label: "Energía & Medioambiente", active: 2, mrr: 5965, arpu: 2982 },
      { label: "Industria & Manufactura", active: 2, mrr: 5428, arpu: 2714 },
    ],
    partners: [
      { name: "Ukabi", clients: 1, mrr: 9658 },
      { name: "Santander", clients: 3, mrr: 6305 },
      { name: "PIHR", clients: 4, mrr: 5905 },
      { name: "Acicatech", clients: 1, mrr: 3247 },
    ],
    strategy: {
      leadChannel: "Partner + Outbound premium play",
      leadChannelDetail: "Partners (43%) + OB (29%) = 72% of MRR. Both deliver €1,600+ ARPU. Inbound ARPU (€302) is near-irrelevant — this is a proactive-only market.",
      partnerPlay: "PIHR is the local anchor, expand with industrial partners",
      partnerDetail: "PIHR (4 clients) is the most consistent local partner. Ukabi contributed €9.6K from 1 deal (Recreational Facilities). Navarra's industrial base (VW, automotive) needs specialized partners.",
      sizeFocus: "M segment = 44% MRR with 90% D2W",
      sizeDetail: "M D2W = 90% (highest in Spain) at €1,470 ARPU. XL contributes 21% from just 4 clients. L is nearly dead (3%). Pure M-market with occasional XL home runs.",
      arpuAssessment: "Highest ARPU in Spain (€1,079). Driven by partner/OB deal quality and M/XL mix. Premium market that should never compete on price.",
      conversionAssessment: "D2W at 83.3% above national. M at 90% is exceptional. Paid at 61% is the weak link — likely wrong audience for this premium market.",
    },
    keyInsights: [
      "Highest ARPU in all of Spain (€1,079) — 48% above national average",
      "M segment D2W = 90% — best in Spain. The M pipeline-to-revenue machine",
      "Inbound ARPU = €302 — lowest of any channel in any major CCAA. Inbound generates wrong-fit leads here",
      "Renewables + Automotive = industrial Navarra. VW factory and wind farms are premium verticals",
      "€/TAM = €62 — second only to Galicia. Extremely efficient revenue per TAM company",
    ],
    openQuestions: [
      "Should we stop inbound investment in Navarra (€302 ARPU, 8% MRR share) and go all OB+Partners?",
      "Can PIHR scale? What's their addressable base within Navarra?",
      "VW Navarra factory supply chain — is there a cluster of automotive suppliers to target?",
      "Renewables at €2,982 ARPU — wind energy installations. Is there a specialized energy partner?",
    ],
  },
  {
    ccaa: "Principado de Asturias",
    code: "AS",
    archetype: "multi-channel",
    tam: 1325,
    hubspot: 547,
    active: 67,
    won: 98,
    demos: 146,
    mrr: 29578,
    arpu: 441,
    d2w: 67.1,
    penetration: 5.1,
    mrrPerTam: 22.3,
    sizes: [
      { label: "S (20-50)", pipeline: 423, active: 44, mrr: 14015, arpu: 319, d2w: 70, mrrShare: 47 },
      { label: "M (51-200)", pipeline: 61, active: 16, mrr: 11340, arpu: 709, d2w: 67, mrrShare: 38 },
      { label: "L (201-500)", pipeline: 29, active: 2, mrr: 631, arpu: 316, d2w: 43, mrrShare: 2 },
      { label: "XL (500+)", pipeline: 24, active: 4, mrr: 3478, arpu: 870, d2w: 43, mrrShare: 12 },
    ],
    provenances: [
      { label: "Inbound", pipeline: 253, active: 14, mrr: 7709, mrrShare: 26, arpu: 551, d2w: 58 },
      { label: "Outbound", pipeline: 140, active: 14, mrr: 7593, mrrShare: 26, arpu: 542, d2w: 85 },
      { label: "Channel Partners", pipeline: 49, active: 15, mrr: 5983, mrrShare: 20, arpu: 399, d2w: 50 },
      { label: "Paid", pipeline: 82, active: 14, mrr: 3409, mrrShare: 12, arpu: 243, d2w: 76 },
      { label: "Telefónica", pipeline: 5, active: 4, mrr: 2269, mrrShare: 8, arpu: 567, d2w: 80 },
      { label: "Santander", pipeline: 9, active: 4, mrr: 1513, mrrShare: 5, arpu: 378, d2w: 50 },
    ],
    industries: [
      { label: "Industria & Manufactura", active: 5, mrr: 4780, arpu: 956 },
      { label: "Energía & Medioambiente", active: 3, mrr: 3204, arpu: 1068 },
      { label: "Distribución & Retail", active: 4, mrr: 2350, arpu: 588 },
    ],
    partners: [
      { name: "Telefonica", clients: 4, mrr: 2269 },
      { name: "Channel Referral Partner", clients: 1, mrr: 1873 },
      { name: "Mercer", clients: 1, mrr: 1050 },
    ],
    strategy: {
      leadChannel: "Outbound is the only path — 85% D2W",
      leadChannelDetail: "OB D2W = 85% vs Partner D2W = 50% vs IB D2W = 58%. Only outbound converts reliably. Inbound volume is high (253 pipeline) but conversion is poor. Redirect resources to OB.",
      partnerPlay: "Minimal partner infrastructure — needs building from scratch",
      partnerDetail: "No meaningful local partner. Telefónica is the only recognizable name (4 clients). This is a greenfield for partner recruitment — but the market size may not justify the investment.",
      sizeFocus: "S-dominated (47% MRR) — smallest deal sizes in Spain",
      sizeDetail: "S ARPU (€319) and M ARPU (€709) are both below national. L segment is essentially non-existent (€631 MRR from 2 clients). This is a micro-SMB market.",
      arpuAssessment: "Lowest ARPU in Spain (€441, 40% below national). Across all sizes and channels, Asturias pays less. Fundamental pricing/product fit question.",
      conversionAssessment: "D2W at 67.1% is 12pp below national. Partner D2W = 50%. Only outbound (85%) achieves acceptable conversion. Systemic quality issue.",
    },
    keyInsights: [
      "Lowest ARPU in Spain (€441) and second-worst D2W (67.1%) — the toughest market",
      "Outbound D2W = 85% — the only channel that works. Partner D2W = 50% — dire",
      "Lowest €/TAM (€22.3) — market revenue extraction is poorest in Spain",
      "Mechanical Engineering and Oil & Energy are the only premium verticals (ARPU > €900)",
      "1,258 untapped TAM — but at €22/TAM, ROI on expansion is questionable without fixing fundamentals",
    ],
    openQuestions: [
      "Is Asturias worth dedicated investment? At €441 ARPU and 67% D2W, the economics are challenging",
      "What's causing the universal underperformance? Product fit? Competitive landscape? Economic factors?",
      "Should Asturias be serviced from Madrid/Galicia rather than having dedicated resources?",
      "Can we find an industrial partner for the Gijón/Oviedo corridor (steel, energy)?",
    ],
  },
  {
    ccaa: "Cantabria",
    code: "CB",
    archetype: "partner-led",
    tam: 863,
    hubspot: 180,
    active: 45,
    won: 53,
    demos: 61,
    mrr: 24267,
    arpu: 539,
    d2w: 86.9,
    penetration: 5.2,
    mrrPerTam: 28.1,
    sizes: [
      { label: "S (20-50)", pipeline: 126, active: 34, mrr: 14167, arpu: 417, d2w: 87, mrrShare: 58 },
      { label: "M (51-200)", pipeline: 30, active: 9, mrr: 9968, arpu: 1108, d2w: 100, mrrShare: 41 },
      { label: "L (201-500)", pipeline: 10, active: 0, mrr: 0, arpu: 0, d2w: null, mrrShare: 0 },
      { label: "XL (500+)", pipeline: 6, active: 0, mrr: 0, arpu: 0, d2w: null, mrrShare: 0 },
    ],
    provenances: [
      { label: "Channel Partners", pipeline: 17, active: 11, mrr: 8399, mrrShare: 35, arpu: 764, d2w: 93 },
      { label: "Paid", pipeline: 30, active: 7, mrr: 4643, mrrShare: 19, arpu: 663, d2w: 67 },
      { label: "Santander", pipeline: 6, active: 4, mrr: 2261, mrrShare: 9, arpu: 565, d2w: 83 },
      { label: "Outbound", pipeline: 52, active: 7, mrr: 2028, mrrShare: 8, arpu: 290, d2w: 73 },
      { label: "Inbound", pipeline: 59, active: 9, mrr: 1930, mrrShare: 8, arpu: 214, d2w: 100 },
      { label: "Telefónica", pipeline: 4, active: 2, mrr: 1413, mrrShare: 6, arpu: 706, d2w: null },
    ],
    industries: [
      { label: "Agroalimentario", active: 4, mrr: 3931, arpu: 983 },
      { label: "Construcción & Inmobiliaria", active: 5, mrr: 3830, arpu: 766 },
      { label: "Servicios Profesionales", active: 3, mrr: 3005, arpu: 1002 },
    ],
    partners: [
      { name: "Acicatech (V Valley)", clients: 8, mrr: 4050 },
      { name: "Integra Consultoría Digital", clients: 1, mrr: 2131 },
      { name: "Telefonica", clients: 2, mrr: 1413 },
    ],
    strategy: {
      leadChannel: "Partner-led with exceptional D2W",
      leadChannelDetail: "Partner D2W = 93% (best of any channel in Cantabria). Overall D2W = 86.9% (3rd best in Spain). Tiny market but converts beautifully through partners.",
      partnerPlay: "Acicatech (V Valley) is the local anchor — scale it",
      partnerDetail: "Acicatech (8 clients, €4K MRR) is the local IT distributor. Small numbers but 93% partner D2W suggests product-market fit is strong when partners bring the leads.",
      sizeFocus: "S+M only — no L/XL market exists",
      sizeDetail: "Zero L/XL active clients. S = 58%, M = 41% of MRR. This is a pure SMB market. Don't try to force enterprise here.",
      arpuAssessment: "Below national (€539 vs €729). S-only market with small companies. M ARPU (€1,108) is decent — grow M share.",
      conversionAssessment: "D2W = 86.9% — 3rd highest. M D2W = 100% (small sample). Partners at 93%. Conversion is excellent — growth comes from pipeline volume.",
    },
    keyInsights: [
      "Partner D2W = 93% — virtually guaranteed conversion through the partner channel",
      "Zero L/XL clients — entirely S+M market. Accept this and optimize for SMB",
      "Acicatech (V Valley) is the de facto Factorial distributor in Cantabria",
      "Food Production (€983 ARPU) and Construction (€766 ARPU) — local industry base",
      "818 untapped TAM — tiny market, but partner-driven with great conversion",
    ],
    openQuestions: [
      "Is Cantabria better served as a Santander/Bilbao satellite rather than standalone region?",
      "Can Acicatech scale from 8 to 20+ clients? What's their addressable reach?",
      "Should Cantabria share AE resources with País Vasco or be serviced remotely?",
      "Food Production (dairy, conservas) — is there a Cantabrian food industry cluster to target?",
    ],
  },
  {
    ccaa: "La Rioja",
    code: "RI",
    archetype: "partner-led",
    tam: 602,
    hubspot: 129,
    active: 20,
    won: 26,
    demos: 38,
    mrr: 16132,
    arpu: 807,
    d2w: 68.4,
    penetration: 3.3,
    mrrPerTam: 26.8,
    sizes: [
      { label: "S (20-50)", pipeline: 87, active: 9, mrr: 6866, arpu: 763, d2w: 68, mrrShare: 43 },
      { label: "M (51-200)", pipeline: 20, active: 6, mrr: 5641, arpu: 940, d2w: 80, mrrShare: 35 },
      { label: "L (201-500)", pipeline: 9, active: 2, mrr: 232, arpu: 116, d2w: null, mrrShare: 1 },
      { label: "XL (500+)", pipeline: 9, active: 2, mrr: 3183, arpu: 1591, d2w: null, mrrShare: 20 },
    ],
    provenances: [
      { label: "Channel Partners", pipeline: 13, active: 5, mrr: 7072, mrrShare: 44, arpu: 1414, d2w: 75 },
      { label: "Paid", pipeline: 23, active: 3, mrr: 3297, mrrShare: 20, arpu: 1099, d2w: 50 },
      { label: "Inbound", pipeline: 54, active: 6, mrr: 2477, mrrShare: 15, arpu: 413, d2w: 89 },
      { label: "Outbound", pipeline: 31, active: 2, mrr: 1711, mrrShare: 11, arpu: 856, d2w: 38 },
      { label: "Santander", pipeline: 6, active: 3, mrr: 1380, mrrShare: 9, arpu: 460, d2w: 80 },
    ],
    industries: [
      { label: "Industria & Manufactura", active: 1, mrr: 4096, arpu: 4096 },
      { label: "Transporte & Logística", active: 2, mrr: 3944, arpu: 1972 },
      { label: "Agroalimentario", active: 2, mrr: 2880, arpu: 1440 },
    ],
    partners: [
      { name: "wellhub", clients: 1, mrr: 4096 },
      { name: "PKF-Attest", clients: 1, mrr: 2472 },
      { name: "Santander", clients: 3, mrr: 1380 },
    ],
    strategy: {
      leadChannel: "Partner-only — too small for direct investment",
      leadChannelDetail: "Partners = 52% MRR. With only 602 TAM and 20 active clients, direct channel investment is hard to justify. Service through partners and Santander.",
      partnerPlay: "Wine industry partner + PKF-Attest expansion",
      partnerDetail: "La Rioja = wine country. Wine & Spirits at €1,440 ARPU. Need a wine industry consultancy/distributor as partner. PKF-Attest and Santander provide baseline coverage.",
      sizeFocus: "S+M (78% MRR) — micro-market",
      sizeDetail: "Only 20 active clients total. S ARPU (€763) is surprisingly high — La Rioja's small companies are higher-value than typical S segment.",
      arpuAssessment: "Above national (€807 vs €729). Small but premium — wine industry and logistics drive quality deals.",
      conversionAssessment: "D2W = 68.4% — below national. Outbound D2W = 38% — don't waste outbound here. Partners and Santander convert better.",
    },
    keyInsights: [
      "Lowest penetration in Spain (3.3%) — virtually untouched market",
      "S ARPU = €763 — highest S-segment ARPU outside Madrid. La Rioja's SMBs are premium",
      "Wine & Spirits: €1,440 ARPU — Rioja DOCa wineries are the natural vertical",
      "OB D2W = 38% — worst OB conversion in Spain. Outbound doesn't work here",
      "Only 582 untapped TAM — partner-only strategy is the realistic approach",
    ],
    openQuestions: [
      "Is 3.3% penetration a sign of untapped potential or structural market ceiling?",
      "Can we recruit a wine industry technology partner or agri-consultant for La Rioja?",
      "Should La Rioja be bundled with Navarra/Aragón for partner and AE coverage?",
      "Logistics (€1,972 ARPU) — Ebro valley corridor logistics companies. Worth a targeted approach?",
    ],
  },
];
