// City → Comunidad Autónoma resolver for strategy_companies.
// 885 CSV municipalities + 250 hand-coded extras + postal/province/pattern fallbacks.

function norm(s: string): string {
  return s
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9 ]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

const M: Record<string, string> = {
  "a coruna": "GA",
  "a estrada": "GA",
  "a guarda": "GA",
  "abanilla": "MC",
  "abrera": "CT",
  "adeje": "CN",
  "aduna": "PV",
  "agost": "VC",
  "agramunt": "CT",
  "aguilas": "MC",
  "aguimes": "CN",
  "ajalvir": "MD",
  "alaior": "IB",
  "albacete": "CM",
  "albal": "VC",
  "alberic": "VC",
  "albolote": "AN",
  "alboraya": "VC",
  "albox": "AN",
  "albuixech": "VC",
  "alcala de guadaira": "AN",
  "alcala de henares": "MD",
  "alcala la real": "AN",
  "alcaniz": "AR",
  "alcantarilla": "MC",
  "alcarras": "CT",
  "alcazar de san juan": "CM",
  "alcobendas": "MD",
  "alcoi": "VC",
  "alcoletge": "CT",
  "alcorcon": "MD",
  "alcorisa": "AR",
  "alcudia": "IB",
  "aldaia": "VC",
  "alella": "CT",
  "alfafar": "VC",
  "alfaro": "RI",
  "algeciras": "AN",
  "algemesi": "VC",
  "algete": "MD",
  "alginet": "VC",
  "alguazas": "MC",
  "alhama de murcia": "MC",
  "alhaurin de la torre": "AN",
  "alicante": "VC",
  "aljaraque": "AN",
  "almaden": "CM",
  "almansa": "CM",
  "almassora": "VC",
  "almazora": "VC",
  "almendralejo": "EX",
  "almeria": "AN",
  "almonte": "AN",
  "almoradi": "VC",
  "almussafes": "VC",
  "alpedrete": "MD",
  "alsasua": "NC",
  "altea": "VC",
  "altorricon": "AR",
  "alzira": "VC",
  "amorebieta": "PV",
  "amorebieta etxano": "PV",
  "amposta": "CT",
  "amurrio": "PV",
  "andoain": "PV",
  "andujar": "AN",
  "anglesola": "CT",
  "antas": "AN",
  "antequera": "AN",
  "arafo": "CN",
  "aranda de duero": "CL",
  "aranjuez": "MD",
  "arazuri": "NC",
  "archena": "MC",
  "arenys de mar": "CT",
  "arganda del rey": "MD",
  "argentona": "CT",
  "armilla": "AN",
  "arnedo": "RI",
  "arona": "CN",
  "arrasate mondragon": "PV",
  "arrecife": "CN",
  "arrigorriaga": "PV",
  "arroyo de la encomienda": "CL",
  "arroyomolinos": "MD",
  "arteixo": "GA",
  "arucas": "CN",
  "aspe": "VC",
  "asteasu": "PV",
  "astigarraga": "PV",
  "atarfe": "AN",
  "autol": "RI",
  "avila": "CL",
  "aviles": "AS",
  "ayamonte": "AN",
  "azkoitia": "PV",
  "azpeitia": "PV",
  "azuqueca de henares": "CM",
  "badajoz": "EX",
  "badalona": "CT",
  "balaguer": "CT",
  "balsicas": "MC",
  "banyeres de mariola": "VC",
  "banyoles": "CT",
  "barakaldo": "PV",
  "baranain": "NC",
  "barbastro": "AR",
  "barbate": "AN",
  "barbera del valles": "CT",
  "barcelona": "CT",
  "basauri": "PV",
  "baza": "AN",
  "beasain": "PV",
  "bejar": "CL",
  "bell lloc d urgell": "CT",
  "bellaterra": "CT",
  "bellpuig": "CT",
  "benalmadena": "AN",
  "benavente": "CL",
  "benicarlo": "VC",
  "benidorm": "VC",
  "beniel": "MC",
  "benifaio": "VC",
  "beniparrell": "VC",
  "benissa": "VC",
  "berga": "CT",
  "bergara": "PV",
  "bergondo": "GA",
  "beriain": "NC",
  "bermeo": "PV",
  "berriozar": "NC",
  "betanzos": "GA",
  "betera": "VC",
  "biar": "VC",
  "bilbao": "PV",
  "binefar": "AR",
  "binissalem": "IB",
  "blanes": "CT",
  "boadilla del monte": "MD",
  "bocairent": "VC",
  "boecillo": "CL",
  "boiro": "GA",
  "bollullos de la mitacion": "AN",
  "borja": "AR",
  "bormujos": "AN",
  "borox": "CM",
  "bueu": "GA",
  "bullas": "MC",
  "bunol": "VC",
  "burgos": "CL",
  "burjassot": "VC",
  "burlada": "NC",
  "burriana": "VC",
  "cabanillas del campo": "CM",
  "cabezo de torres": "MC",
  "cabra": "AN",
  "cabrera de mar": "CT",
  "caceres": "EX",
  "cadiz": "AN",
  "cadrete": "AR",
  "cala millor": "IB",
  "calaf": "CT",
  "calafell": "CT",
  "calahorra": "RI",
  "calasparra": "MC",
  "calatayud": "AR",
  "caldes de montbui": "CT",
  "calella": "CT",
  "callosa de segura": "VC",
  "calp": "VC",
  "calvia": "IB",
  "camargo": "CB",
  "camas": "AN",
  "cambre": "GA",
  "cambrils": "CT",
  "campo de criptana": "CM",
  "campos": "IB",
  "canals": "VC",
  "candelaria": "CN",
  "cangas": "GA",
  "cangas del narcea": "AS",
  "canovelles": "CT",
  "cantoria": "AN",
  "capdepera": "IB",
  "capellades": "CT",
  "carbajosa de la sagrada": "CL",
  "carballo": "GA",
  "carcaixent": "VC",
  "cardedeu": "CT",
  "carlet": "VC",
  "carmona": "AN",
  "carral": "GA",
  "carreno": "AS",
  "cartagena": "MC",
  "casarrubuelos": "CM",
  "casetas": "AR",
  "caspe": "AR",
  "cassa de la selva": "CT",
  "castalla": "VC",
  "castellar del valles": "CT",
  "castellbisbal": "CT",
  "castelldefels": "CT",
  "castello de la plana": "VC",
  "castrillon": "AS",
  "castro urdiales": "CB",
  "catarroja": "VC",
  "catral": "MC",
  "caudete": "CM",
  "celra": "CT",
  "centelles": "CT",
  "cerceda": "GA",
  "cerdanyola del valles": "CT",
  "cervera": "CT",
  "ceuta": "CE",
  "ceuti": "MC",
  "cheste": "VC",
  "chiclana de la frontera": "AN",
  "chipiona": "AN",
  "chiva": "VC",
  "churriana de la vega": "AN",
  "ciempozuelos": "MD",
  "cieza": "MC",
  "ciudad real": "CM",
  "ciudad rodrigo": "CL",
  "ciutadella de menorca": "IB",
  "cocentaina": "VC",
  "coles": "GA",
  "collado villalba": "MD",
  "colmenar viejo": "MD",
  "conil de la frontera": "AN",
  "constanti": "CT",
  "consuegra": "CM",
  "corbera": "CT",
  "cordoba": "AN",
  "cordovilla": "NC",
  "corella": "NC",
  "coria": "EX",
  "coria del rio": "AN",
  "cornella de llobregat": "CT",
  "cornella del terri": "CT",
  "corvera de asturias": "AS",
  "coslada": "MD",
  "costa adeje": "CN",
  "costa teguise": "CN",
  "crevillent": "VC",
  "cuarte de huerva": "AR",
  "cubelles": "CT",
  "cuenca": "CM",
  "cuevas del almanzora": "AN",
  "cullera": "VC",
  "culleredo": "GA",
  "curtis": "GA",
  "daganzo de arriba": "MD",
  "daimiel": "CM",
  "deltebre": "CT",
  "denia": "VC",
  "derio": "PV",
  "don benito": "EX",
  "donostia san sebastian": "PV",
  "dos hermanas": "AN",
  "durango": "PV",
  "ecija": "AN",
  "eibar": "PV",
  "eivissa": "IB",
  "ejea de los caballeros": "AR",
  "el algar": "MC",
  "el astillero": "CB",
  "el burgo de ebro": "AR",
  "el ejido": "AN",
  "el masnou": "CT",
  "el prat de llobregat": "CT",
  "el puerto de santa maria": "AN",
  "el puntal": "MC",
  "el raal": "MC",
  "el rosario": "CN",
  "el vendrell": "CT",
  "el viso del alcor": "AN",
  "elche": "VC",
  "elda": "VC",
  "elgoibar": "PV",
  "elorrio": "PV",
  "empuriabrava": "CT",
  "epila": "AR",
  "erandio": "PV",
  "errenteria": "PV",
  "esparreguera": "CT",
  "espinardo": "MC",
  "esplugues de llobregat": "CT",
  "estella lizarra": "NC",
  "estepa": "AN",
  "estepona": "AN",
  "felanitx": "IB",
  "ferrol": "GA",
  "figueres": "CT",
  "figueruelas": "AR",
  "finestrat": "VC",
  "foios": "VC",
  "fornells de la selva": "CT",
  "fortuna": "MC",
  "fraga": "AR",
  "fuengirola": "AN",
  "fuenlabrada": "MD",
  "fuente alamo": "MC",
  "fuente alamo de murcia": "MC",
  "galapagar": "MD",
  "galdakao": "PV",
  "gallur": "AR",
  "gandia": "VC",
  "gava": "CT",
  "gelida": "CT",
  "getafe": "MD",
  "getxo": "PV",
  "gijon": "AS",
  "gines": "AN",
  "girona": "CT",
  "godella": "VC",
  "gondomar": "GA",
  "granada": "AN",
  "granadilla de abona": "CN",
  "granja de rocamora": "VC",
  "granollers": "CT",
  "grinon": "MD",
  "guadalajara": "CM",
  "guadarrama": "MD",
  "guarnizo": "CB",
  "guijuelo": "CL",
  "guimar": "CN",
  "gurb": "CT",
  "haro": "RI",
  "hellin": "CM",
  "heras": "CB",
  "herencia": "CM",
  "hernani": "PV",
  "huarte": "NC",
  "huelva": "AN",
  "huercal de almeria": "AN",
  "huesca": "AR",
  "humanes de madrid": "MD",
  "ibi": "VC",
  "idiazabal": "PV",
  "igualada": "CT",
  "illescas": "CM",
  "inca": "IB",
  "ingenio": "CN",
  "irun": "PV",
  "iruna": "NC",
  "iurreta": "PV",
  "jaca": "AR",
  "jaen": "AN",
  "jerez de la frontera": "AN",
  "jumilla": "MC",
  "l alcora": "VC",
  "l aldea": "CT",
  "l alfas del pi": "VC",
  "l ametlla del valles": "CT",
  "l arboc": "CT",
  "l eliana": "VC",
  "l hospitalet de llobregat": "CT",
  "l olleria": "VC",
  "la bisbal d emporda": "CT",
  "la garriga": "CT",
  "la laguna": "CN",
  "la linea de la concepcion": "AN",
  "la llagosta": "CT",
  "la mojonera": "AN",
  "la muela": "AR",
  "la nucia": "VC",
  "la orotava": "CN",
  "la pobla de claramunt": "CT",
  "la pobla de vallbona": "VC",
  "la rambla": "AN",
  "la rinconada": "AN",
  "la roca del valles": "CT",
  "la roda": "AN",
  "la senia": "VC",
  "la union": "MC",
  "la vall d uixo": "VC",
  "laguardia": "RI",
  "lalin": "GA",
  "langreo": "AS",
  "lardero": "RI",
  "laredo": "CB",
  "las palmas": "CN",
  "las palmas de gran canaria": "CN",
  "las rozas": "MD",
  "las rozas de madrid": "MD",
  "las torres de cotillas": "MC",
  "lasarte oria": "PV",
  "lebrija": "AN",
  "leganes": "MD",
  "leioa": "PV",
  "leon": "CL",
  "lepe": "AN",
  "les franqueses del valles": "CT",
  "librilla": "MC",
  "linares": "AN",
  "llanera": "AS",
  "llanes": "AS",
  "lleida": "CT",
  "llers": "CT",
  "llica de vall": "CT",
  "llinars del valles": "CT",
  "lliria": "VC",
  "llodio": "PV",
  "lloret de mar": "CT",
  "llucmajor": "IB",
  "lodosa": "NC",
  "loeches": "MD",
  "logrono": "RI",
  "loiu": "PV",
  "lorca": "MC",
  "lorqui": "MC",
  "los barrios": "AN",
  "los palacios y villafranca": "AN",
  "los realejos": "CN",
  "los yebenes": "CM",
  "lucena": "AN",
  "lugo": "GA",
  "lugones": "AS",
  "madrid": "MD",
  "madridejos": "CM",
  "mairena del aljarafe": "AN",
  "majadahonda": "MD",
  "malaga": "AN",
  "malgrat de mar": "CT",
  "maliano": "CB",
  "mallorca": "IB",
  "manacor": "IB",
  "mancha real": "AN",
  "manilva": "AN",
  "manises": "VC",
  "manlleu": "CT",
  "manresa": "CT",
  "manzanares": "CM",
  "mao": "IB",
  "maracena": "AN",
  "marbella": "AN",
  "marchena": "AN",
  "marin": "GA",
  "marratxi": "IB",
  "martorell": "CT",
  "martorelles": "CT",
  "martos": "AN",
  "maspalomas": "CN",
  "masquefa": "CT",
  "massalfassar": "VC",
  "massamagrell": "VC",
  "massanassa": "VC",
  "mataro": "CT",
  "mazarron": "MC",
  "meco": "MD",
  "medina del campo": "CL",
  "medio cudeyo": "CB",
  "mejorada del campo": "MD",
  "melilla": "ML",
  "mengibar": "AN",
  "merida": "EX",
  "mieres": "AS",
  "mieres del camino": "AS",
  "miguelturra": "CM",
  "mijas": "AN",
  "milagro": "NC",
  "miraflores de la sierra": "MD",
  "miranda de ebro": "CL",
  "mislata": "VC",
  "moana": "GA",
  "mogan": "CN",
  "moguer": "AN",
  "molina de segura": "MC",
  "molins de rei": "CT",
  "mollerussa": "CT",
  "mollet del valles": "CT",
  "moncada": "VC",
  "monesterio": "EX",
  "montblanc": "CT",
  "montcada i reixac": "CT",
  "montijo": "EX",
  "montilla": "AN",
  "montmelo": "CT",
  "montornes del valles": "CT",
  "monzon": "AR",
  "moraira": "VC",
  "morana": "GA",
  "mos": "GA",
  "mostoles": "MD",
  "motril": "AN",
  "muel": "AR",
  "mula": "MC",
  "mungia": "PV",
  "murcia": "MC",
  "muro": "IB",
  "muro d alcoi": "VC",
  "museros": "VC",
  "mutilva": "NC",
  "mutilva baja": "NC",
  "najera": "RI",
  "naquera": "VC",
  "naron": "GA",
  "navalcarnero": "MD",
  "navalmoral de la mata": "EX",
  "navarrete": "RI",
  "navia": "AS",
  "nerja": "AN",
  "nigran": "GA",
  "noain": "NC",
  "novelda": "VC",
  "nules": "VC",
  "o grove": "GA",
  "ogijares": "AN",
  "oiartzun": "PV",
  "oleiros": "GA",
  "olesa de montserrat": "CT",
  "oliva": "VC",
  "olmedo": "CL",
  "olot": "CT",
  "onati": "PV",
  "onda": "VC",
  "ondara": "VC",
  "onil": "VC",
  "ontinyent": "VC",
  "onzonilla": "CL",
  "orcoyen": "NC",
  "ordes": "GA",
  "orihuela": "VC",
  "orio": "PV",
  "orkoien": "NC",
  "ortuella": "PV",
  "osuna": "AN",
  "ourense": "GA",
  "oviedo": "AS",
  "padron": "GA",
  "paiporta": "VC",
  "palafolls": "CT",
  "palafrugell": "CT",
  "palau solita i plegamans": "CT",
  "palencia": "CL",
  "palleja": "CT",
  "palma": "IB",
  "palos de la frontera": "AN",
  "pamplona": "NC",
  "pantoja": "CM",
  "paracuellos de jarama": "MD",
  "parets del valles": "CT",
  "parla": "MD",
  "paterna": "VC",
  "pedreguer": "VC",
  "pedrola": "AR",
  "peligros": "AN",
  "penafiel": "CL",
  "peralta": "NC",
  "petrer": "VC",
  "picanya": "VC",
  "picassent": "VC",
  "pielagos": "CB",
  "pilar de la horadada": "VC",
  "pineda de mar": "CT",
  "pinto": "MD",
  "plasencia": "EX",
  "playa blanca": "CN",
  "playa de las americas": "CN",
  "poio": "GA",
  "polinya": "CT",
  "ponferrada": "CL",
  "ponteareas": "GA",
  "pontedeume": "GA",
  "pontevedra": "GA",
  "port de soller": "IB",
  "portals nous": "IB",
  "portugalete": "PV",
  "pozoblanco": "AN",
  "pozuelo de alarcon": "MD",
  "pucol": "VC",
  "puente genil": "AN",
  "puerto de la cruz": "CN",
  "puerto del carmen": "CN",
  "puerto del rosario": "CN",
  "puerto lumbreras": "MC",
  "puerto real": "AN",
  "puertollano": "CM",
  "puigpunyent": "IB",
  "quart de poblet": "VC",
  "quintanar de la orden": "CM",
  "rafelbunyol": "VC",
  "redondela": "GA",
  "reinosa": "CB",
  "requena": "VC",
  "reus": "CT",
  "riba roja de turia": "VC",
  "ribadumia": "GA",
  "ripoll": "CT",
  "ripollet": "CT",
  "riudellots de la selva": "CT",
  "riudoms": "CT",
  "rivas vaciamadrid": "MD",
  "ronda": "AN",
  "roquetas de mar": "AN",
  "roses": "CT",
  "rubi": "CT",
  "rute": "AN",
  "sabadell": "CT",
  "sabinanigo": "AR",
  "sada": "GA",
  "sagunto": "VC",
  "salamanca": "CL",
  "sallent": "CT",
  "salou": "CT",
  "salt": "CT",
  "salteras": "AN",
  "salvaterra de mino": "GA",
  "sama": "AS",
  "san andres del rabanedo": "CL",
  "san bartolome de tirajana": "CN",
  "san cristobal de la laguna": "CN",
  "san fernando": "AN",
  "san fernando de henares": "MD",
  "san javier": "MC",
  "san jose de la rinconada": "AN",
  "san martin de la vega": "MD",
  "san martin de valdeiglesias": "MD",
  "san miguel de abona": "CN",
  "san pedro alcantara": "AN",
  "san pedro del pinatar": "MC",
  "san roque": "AN",
  "san sebastian": "PV",
  "san sebastian de los reyes": "MD",
  "sanguesa": "NC",
  "sanlucar de barrameda": "AN",
  "sant adria de besos": "CT",
  "sant andreu de la barca": "CT",
  "sant antoni de portmany": "IB",
  "sant boi de llobregat": "CT",
  "sant celoni": "CT",
  "sant cugat del valles": "CT",
  "sant esteve sesrovires": "CT",
  "sant feliu de llobregat": "CT",
  "sant fruitos de bages": "CT",
  "sant joan d alacant": "VC",
  "sant joan de vilatorrada": "CT",
  "sant joan despi": "CT",
  "sant joan les fonts": "CT",
  "sant jordi de ses salines": "IB",
  "sant just desvern": "CT",
  "sant pere pescador": "CT",
  "sant quirze del valles": "CT",
  "sant sadurni d anoia": "CT",
  "sant vicenc dels horts": "CT",
  "sant vicent del raspeig": "VC",
  "santa coloma de gramenet": "CT",
  "santa cruz de bezana": "CB",
  "santa cruz de la palma": "CN",
  "santa cruz de tenerife": "CN",
  "santa eulalia des riu": "IB",
  "santa eularia des riu": "IB",
  "santa lucia de tirajana": "CN",
  "santa perpetua de mogoda": "CT",
  "santa pola": "VC",
  "santa ponsa": "IB",
  "santa susanna": "CT",
  "santander": "CB",
  "santiago de compostela": "GA",
  "santiponce": "AN",
  "santomera": "MC",
  "santona": "CB",
  "santpedor": "CT",
  "santurtzi": "PV",
  "sanxenxo": "GA",
  "sarriguren": "NC",
  "sax": "VC",
  "segovia": "CL",
  "sentmenat": "CT",
  "sesena nuevo": "CM",
  "sestao": "PV",
  "sevilla": "AN",
  "siero": "AS",
  "silla": "VC",
  "silleda": "GA",
  "sils": "CT",
  "sitges": "CT",
  "soller": "IB",
  "solsona": "CT",
  "soria": "CL",
  "sotogrande": "AN",
  "tacoronte": "CN",
  "tafalla": "NC",
  "tajonar": "NC",
  "talavera de la reina": "CM",
  "tarancon": "CM",
  "tarifa": "AN",
  "tarragona": "CT",
  "tarrega": "CT",
  "telde": "CN",
  "terrassa": "CT",
  "teruel": "AR",
  "teulada": "VC",
  "tias": "CN",
  "tineo": "AS",
  "toledo": "CM",
  "tolosa": "PV",
  "tomares": "AN",
  "tomelloso": "CM",
  "tona": "CT",
  "tordera": "CT",
  "tordesillas": "CL",
  "torre del mar": "AN",
  "torre pacheco": "MC",
  "torredembarra": "CT",
  "torrefarrera": "CT",
  "torrejon de ardoz": "MD",
  "torrelavega": "CB",
  "torrelodones": "MD",
  "torremolinos": "AN",
  "torrent": "VC",
  "torres de la alameda": "MD",
  "torrevieja": "VC",
  "tortosa": "CT",
  "tossa de mar": "CT",
  "totana": "MC",
  "tres cantos": "MD",
  "trujillo": "EX",
  "tudela": "NC",
  "tui": "GA",
  "ubeda": "AN",
  "ubrique": "AN",
  "urnieta": "PV",
  "utebo": "AR",
  "utrera": "AN",
  "vacarisses": "CT",
  "valdemoro": "MD",
  "valdepenas": "CM",
  "valderrobres": "AR",
  "valencia": "VC",
  "valladolid": "CL",
  "vallirana": "CT",
  "valls": "CT",
  "valverde del majano": "CL",
  "velez malaga": "AN",
  "velilla de san antonio": "MD",
  "venta de banos": "CL",
  "vera": "AN",
  "viator": "AN",
  "vic": "CT",
  "vigo": "GA",
  "vila real": "VC",
  "vila seca": "CT",
  "vilablareix": "CT",
  "vilaboa": "GA",
  "viladecans": "CT",
  "viladecavalls": "CT",
  "vilafranca del penedes": "CT",
  "vilagarcia de arousa": "GA",
  "vilamalla": "CT",
  "vilamarxant": "VC",
  "vilanova i la geltru": "CT",
  "vilassar de dalt": "CT",
  "vilassar de mar": "CT",
  "villajoyosa": "VC",
  "villamalea": "CM",
  "villanueva de gallego": "AR",
  "villanueva de la canada": "MD",
  "villanueva de la serena": "EX",
  "villares de la reina": "CL",
  "villarrobledo": "CM",
  "villarrubia de los ojos": "CM",
  "villatuerta": "NC",
  "villava": "NC",
  "villaviciosa de odon": "MD",
  "villena": "VC",
  "vinaros": "VC",
  "vitoria gasteiz": "PV",
  "viveiro": "GA",
  "xabia": "VC",
  "xativa": "VC",
  "xeraco": "VC",
  "xirivella": "VC",
  "xixona": "VC",
  "yecla": "MC",
  "yeles": "CM",
  "yuncler": "CM",
  "yuncos": "CM",
  "zafra": "EX",
  "zamora": "CL",
  "zamudio": "PV",
  "zaragoza": "AR",
  "zarautz": "PV",
  "zierbena": "PV",
  "zizur mayor": "NC",
  "zuera": "AR",
  "zumaia": "PV",
  "seville": "AN",
  "rincon de la victoria": "AN",
  "moron de la frontera": "AN",
  "baeza": "AN",
  "alhaurin el grande": "AN",
  "arroyo de la miel": "AN",
  "porrino": "GA",
  "hospitalet de llobregat": "CT",
  "palamos": "CT",
  "sant feliu de guixols": "CT",
  "sant feliu de codines": "CT",
  "dosrius": "CT",
  "vilafant": "CT",
  "castellar de la frontera": "AN",
  "sant pere de ribes": "CT",
  "canet de mar": "CT",
  "aiguaviva": "CT",
  "premia de dalt": "CT",
  "premia de mar": "CT",
  "vilanova del cami": "CT",
  "corbera de llobregat": "CT",
  "arganda": "MD",
  "torrejon de la calzada": "MD",
  "brunete": "MD",
  "villalbilla": "MD",
  "moralzarzal": "MD",
  "colmenar de oreja": "MD",
  "san lorenzo de el escorial": "MD",
  "villanueva del pardillo": "MD",
  "cercedilla": "MD",
  "chinchon": "MD",
  "sesena": "CM",
  "donostia": "PV",
  "gasteiz vitoria": "PV",
  "vitoria": "PV",
  "bilbo": "PV",
  "bilbao bilbo": "PV",
  "gasteiz": "PV",
  "olaberria": "PV",
  "usurbil": "PV",
  "lasarte": "PV",
  "bizkaia": "PV",
  "trapagaran": "PV",
  "alacant": "VC",
  "elx": "VC",
  "alicante alacant": "VC",
  "el campello": "VC",
  "san vicent del raspeig": "VC",
  "alaquas": "VC",
  "castellon": "VC",
  "javea": "VC",
  "l alcudia": "VC",
  "benicassim": "VC",
  "ribarroja del turia": "VC",
  "castellon de la plana": "VC",
  "alcasser": "VC",
  "palma de mallorca": "IB",
  "ibiza": "IB",
  "sant josep de sa talaia": "IB",
  "pollenca": "IB",
  "andratx": "IB",
  "can picafort": "IB",
  "santanyi": "IB",
  "corralejo": "CN",
  "port d andratx": "IB",
  "pola de siero": "AS",
  "la coruna": "GA",
  "o milladoiro": "GA",
  "laracha": "GA",
  "sarria": "GA",
  "vilanova de la barca": "CT",
  "cambados": "GA",
  "arteijo": "GA",
  "las galletas": "CN",
  "vecindario": "CN",
  "arinaga": "CN",
  "tegueste": "CN",
  "los cristianos": "CN",
  "sauzal": "CN",
  "villaquilambre": "CL",
  "laguna de duero": "CL",
  "aguilar de campoo": "CL",
  "santovenia de pisuerga": "CL",
  "bembibre": "CL",
  "olivenza": "EX",
  "fregenal de la sierra": "EX",
  "san gines": "MC",
  "pinseque": "AR",
  "cartuja baja": "AR",
  "la puebla de alfinden": "AR",
  "maria de huerva": "AR",
  "alfamen": "AR",
  "torrijos": "CM",
  "olias del rey": "CM",
  "revilla de camargo": "CB",
  "santiago": "GA",
  "victoria": "PV",
};

const X: Record<string, string> = {
  "abaran": "MC", "adra": "AN", "agoncillo": "RI", "albatera": "VC",
  "albondon": "AN", "alboraia": "VC", "alburquerque": "EX",
  "alcover": "CT", "alcoy": "VC", "alcoi": "VC",
  "algimia de alfara": "VC", "almazan": "CL", "almodovar del campo": "CM",
  "ames": "GA", "arbizu": "NC", "arbo": "GA",
  "arcos de la frontera": "AN", "arenys de munt": "CT", "arico": "CN",
  "artes": "CT", "artesa de lleida": "CT", "arzua": "GA", "asco": "CT",
  "astillero": "CB", "el astillero": "CB", "anora": "AN",
  "abadino": "PV", "ablitas": "NC", "adamuz": "AN", "ademuz": "VC",
  "ador": "VC", "aguadulce": "AN", "aguilar": "AN", "ahillones": "EX",
  "aielo de malferit": "VC", "aiguafreda": "CT", "aitona": "CT",
  "aizoain": "NC", "ajofrin": "CM", "alacant alicante": "VC",
  "alagon del rio": "EX", "baena": "AN", "barbadas": "GA",
  "basuri": "PV", "banos y mendigo": "MC", "bcn": "CT",
  "bellreguard": "VC", "bembezar": "AN", "benaguacil": "VC",
  "benaguasil": "VC", "benajarafe": "AN", "benalmadena costa": "AN",
  "bigues i riells": "CT", "boadillas del monte": "MD",
  "bollullos par del condado": "AN", "bolnuevo": "MC", "boquineni": "AR",
  "bugarra": "VC", "burgohondo": "CL", "cabanas de la sagra": "CM",
  "cabrils": "CT", "cacicedo": "CB", "calonge": "CT", "calpe": "VC",
  "canyelles": "CT", "cartaya": "AN", "casas de juan nunez": "CM",
  "castellgali": "CT", "castelloli": "CT", "cellers": "CT",
  "cenes de la vega": "AN", "chane": "CL", "chiclana": "AN",
  "ciudda real": "CM", "colmenarejo": "MD", "costa calma": "CN",
  "cox": "VC", "crevillente": "VC", "el papiol": "CT",
  "el puerto santa maria": "AN", "elche de la sierra": "CM",
  "els alamus": "CT", "es pelats": "IB", "espartinas": "AN",
  "faura": "VC", "felechosa aller": "AS", "fene": "GA",
  "fogars de la selva": "CT", "fresno de la vega": "CL",
  "fuensalida": "CM", "garray": "CL", "gelves": "AN", "ginez": "AN",
  "grijota": "CL", "guardamar del segura": "VC", "guardo": "CL",
  "guia de isora": "CN", "hinojedo": "CB", "hornachuelos": "AN",
  "iscar": "CL", "isla mayor": "AN", "la baneza": "CL",
  "la horra": "CL", "la puebla de cazalla": "AN", "la solana": "CM",
  "las franquesas del valles": "CT", "ledono": "GA", "llieda": "CT",
  "lora del rio": "AN", "loriguilla": "VC", "lousame": "GA",
  "lametlla del valles": "CT", "mahon": "IB", "mairena del alcor": "AN",
  "malagon": "CM", "medina del camp": "CL", "mendaro": "PV",
  "mijas costa": "AN", "milladoiro": "GA", "minglanilla": "CM",
  "mocada": "VC", "moixent": "VC", "mollina": "AN", "monovar": "VC",
  "monserrat": "VC", "montcada y reixac": "CT", "montemayor": "AN",
  "o porrino": "GA", "ocana": "CM", "ochavillo del rio": "AN",
  "oliva de merida": "EX", "olvega": "CL", "orellana la vieja": "EX",
  "orihuela costa": "VC", "oroso": "GA", "pajara": "CN",
  "palacios y villafranca": "AN", "palma de mallorc": "IB", "pals": "CT",
  "patino": "MC", "picon": "CM", "piera": "CT",
  "playa del ingles": "CN", "pobla": "VC", "pobla de vallbona": "VC",
  "poblete": "CM", "pozuelo": "MD", "presencio": "CL",
  "priego de cordoba": "AN", "puebla de la calza": "EX",
  "puerto de sagunto": "VC", "puig reig": "CT", "pulpi": "AN",
  "puntallana": "CN", "real de san vicente": "CM", "riogordo": "AN",
  "rios": "GA", "roda de bara": "CT", "rodonya": "CT", "rota": "AN",
  "sabiote": "AN", "san cibrao das vinas": "GA", "san ciprian": "GA",
  "san juan de alicante": "VC", "san juan del puerto": "AN",
  "san juan pto": "AN", "san vicent de la cala": "VC",
  "sangonera la verde": "MC", "sant cugat": "CT", "sant joanet": "VC",
  "sant jordi": "VC", "sant marti de centelles": "CT",
  "sant quinti de mediona": "CT", "santa cruz bezana": "CB",
  "santa cruz tenerife": "CN", "sc de tenerife": "CN",
  "sc tenerife": "CN", "santa eulalia del rio": "IB",
  "santa gertrudis": "IB", "santa margarida i els monjos": "CT",
  "santa maria de palautordera": "CT", "santa maria del mar": "CN",
  "sorzano": "RI", "suances": "CB", "sueca": "VC", "tahiche": "CN",
  "tavernes de la valldigna": "VC", "teguise": "CN", "tiana": "CT",
  "tobarra": "CM", "tordoia": "GA", "torre del pla": "CT",
  "torregrossa": "CT", "torrejon de velasco": "MD", "val do dubra": "GA",
  "valencina de la concepcion": "AN", "valle de trapaga": "PV",
  "valverde del camino": "AN", "venta del pobre": "AN",
  "vidreres": "CT", "vielha": "CT", "villagonzalo pedernales": "CL",
  "villalon de campos": "CL", "villanueva de la reina": "AN",
  "villar del rey": "EX", "villaverde alto": "MD",
  "villaverde del rio": "AN", "vimianzo": "GA",
  "a igrexa": "GA", "a laracha": "GA", "a mezquita": "GA",
  "a zamorana": "GA", "acantilados de los gigantes": "CN",
  "aeropuerto reina sofia": "CN", "agua de fontanales": "CN",
  "san miguel": "CN",
  "greater madrid metropolitan area": "MD",
  "greater barcelona metropolitan area": "CT",
  "greater bilbao metropolitan area": "PV",
  "greater valencia metropolitan area": "VC",
  "greater seville metropolitan area": "AN",
  "greater malaga metropolitan area": "AN",
};

const P: Record<string, string> = {
  alava: "PV", albacete: "CM", alicante: "VC", almeria: "AN",
  asturias: "AS", avila: "CL", badajoz: "EX", baleares: "IB",
  "islas baleares": "IB", barcelona: "CT", bizkaia: "PV", vizcaya: "PV",
  burgos: "CL", caceres: "EX", cadiz: "AN", cantabria: "CB",
  castellon: "VC", "ciudad real": "CM", cordoba: "AN", coruna: "GA",
  "a coruna": "GA", "la coruna": "GA", cuenca: "CM", gipuzkoa: "PV",
  guipuzcoa: "PV", girona: "CT", gerona: "CT", granada: "AN",
  guadalajara: "CM", huelva: "AN", huesca: "AR", jaen: "AN",
  "la rioja": "RI", "las palmas": "CN", leon: "CL", lleida: "CT",
  lerida: "CT", lugo: "GA", madrid: "MD", malaga: "AN", murcia: "MC",
  navarra: "NC", ourense: "GA", orense: "GA", palencia: "CL",
  pontevedra: "GA", salamanca: "CL", "santa cruz de tenerife": "CN",
  tenerife: "CN", segovia: "CL", sevilla: "AN", soria: "CL",
  tarragona: "CT", teruel: "AR", toledo: "CM", valencia: "VC",
  valladolid: "CL", zamora: "CL", zaragoza: "AR",
  "gran canaria": "CN", lanzarote: "CN", fuerteventura: "CN",
  "la palma": "CN", "la gomera": "CN", mallorca: "IB", menorca: "IB",
  ibiza: "IB", formentera: "IB", ceuta: "CE", melilla: "ML",
};

const CP: Record<string, string> = {
  "01": "PV", "02": "CM", "03": "VC", "04": "AN", "05": "CL", "06": "EX",
  "07": "IB", "08": "CT", "09": "CL", "10": "EX", "11": "AN", "12": "VC",
  "13": "CM", "14": "AN", "15": "GA", "16": "CM", "17": "CT", "18": "AN",
  "19": "CM", "20": "PV", "21": "AN", "22": "AR", "23": "AN", "24": "CL",
  "25": "CT", "26": "RI", "27": "GA", "28": "MD", "29": "AN", "30": "MC",
  "31": "NC", "32": "GA", "33": "AS", "34": "CL", "35": "CN", "36": "GA",
  "37": "CL", "38": "CN", "39": "CB", "40": "CL", "41": "AN", "42": "CL",
  "43": "CT", "44": "AR", "45": "CM", "46": "VC", "47": "CL", "48": "PV",
  "49": "CL", "50": "AR", "51": "CE", "52": "ML",
};

const NAMES: Record<string, string> = {
  AN: "Andalucía", AR: "Aragón", AS: "Principado de Asturias",
  IB: "Islas Baleares", CN: "Canarias", CB: "Cantabria",
  CL: "Castilla y León", CM: "Castilla-La Mancha", CT: "Cataluña",
  VC: "Comunidad Valenciana", EX: "Extremadura", GA: "Galicia",
  MD: "Comunidad de Madrid", MC: "Región de Murcia",
  NC: "Comunidad Foral de Navarra", PV: "País Vasco", RI: "La Rioja",
  CE: "Ceuta", ML: "Melilla",
};

export interface CcaaResult { ccaa: string; code: string }

function lookup(n: string): string | undefined {
  return M[n] ?? X[n];
}

export function resolveCCAA(raw: string): CcaaResult {
  const UNK: CcaaResult = { ccaa: "Unknown", code: "??" };
  if (!raw || raw === "-" || raw === "masked data") return UNK;

  const n = norm(raw);
  const d = lookup(n);
  if (d) return { ccaa: NAMES[d] ?? "Unknown", code: d };

  const parts = raw.split(",").map((s) => s.trim());
  const nbc = norm(parts[0]);
  const bc = lookup(nbc);
  if (bc) return { ccaa: NAMES[bc] ?? "Unknown", code: bc };

  for (let i = 1; i < parts.length; i++) {
    const s = norm(parts[i]);
    if (!s || s === "selection not available" || s === "spain") continue;
    const pv = P[s];
    if (pv) return { ccaa: NAMES[pv] ?? "Unknown", code: pv };
    const city = lookup(s);
    if (city) return { ccaa: NAMES[city] ?? "Unknown", code: city };
  }

  const pm = raw.match(/^(\d{4,5})\s*,?\s*(.*)/);
  if (pm) {
    const cp = pm[1].padStart(5, "0");
    const rest = norm(pm[2]);
    if (rest) { const c = lookup(rest); if (c) return { ccaa: NAMES[c] ?? "Unknown", code: c }; }
    const prefix = cp.substring(0, 2);
    const pc = CP[prefix];
    if (pc) return { ccaa: NAMES[pc] ?? "Unknown", code: pc };
  }

  const am = raw.match(/Administrative State[\.\ ]+(.*)/i);
  if (am) {
    const adm = norm(am[1]);
    const pv = P[adm]; if (pv) return { ccaa: NAMES[pv] ?? "Unknown", code: pv };
    const c = lookup(adm); if (c) return { ccaa: NAMES[c] ?? "Unknown", code: c };
  }

  const np = norm(raw.replace(/\s*\(.*?\)\s*/g, " "));
  if (np !== n) { const c = lookup(np); if (c) return { ccaa: NAMES[c] ?? "Unknown", code: c }; }

  const df = norm(raw.split("-")[0]);
  if (df !== n) { const c = lookup(df); if (c) return { ccaa: NAMES[c] ?? "Unknown", code: c }; }

  const pv = P[n] ?? P[nbc];
  if (pv) return { ccaa: NAMES[pv] ?? "Unknown", code: pv };

  const gm = n.match(/^greater\s+(.+?)(\s+metropolitan)?(\s+area)?(\s+spain)?$/);
  if (gm) {
    const city = gm[1];
    const c = lookup(city) ?? P[city];
    if (c) return { ccaa: NAMES[c] ?? "Unknown", code: c };
  }

  const words = nbc.split(" ");
  for (let len = Math.min(words.length, 5); len >= 2; len--) {
    const sub = words.slice(0, len).join(" ");
    const c = lookup(sub);
    if (c) return { ccaa: NAMES[c] ?? "Unknown", code: c };
  }

  return UNK;
}

export const CCAA_LIST = [
  "Andalucía", "Aragón", "Principado de Asturias", "Islas Baleares",
  "Canarias", "Cantabria", "Castilla y León", "Castilla-La Mancha",
  "Cataluña", "Comunidad Valenciana", "Extremadura", "Galicia",
  "Comunidad de Madrid", "Región de Murcia", "Comunidad Foral de Navarra",
  "País Vasco", "La Rioja", "Ceuta", "Melilla", "Unknown",
];
