/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TableRouteImport } from './routes/table'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as IcpRouteImport } from './routes/icp'
import { Route as HubspotUsageRouteImport } from './routes/hubspot-usage'
import { Route as EnrichmentRouteImport } from './routes/enrichment'
import { Route as DataCleaningRouteImport } from './routes/data-cleaning'
import { Route as BlitzDayRouteImport } from './routes/blitz-day'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegionsIndexRouteImport } from './routes/regions.index'
import { Route as RegionsCodeRouteImport } from './routes/regions.$code'

const TableRoute = TableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IcpRoute = IcpRouteImport.update({
  id: '/icp',
  path: '/icp',
  getParentRoute: () => rootRouteImport,
} as any)
const HubspotUsageRoute = HubspotUsageRouteImport.update({
  id: '/hubspot-usage',
  path: '/hubspot-usage',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrichmentRoute = EnrichmentRouteImport.update({
  id: '/enrichment',
  path: '/enrichment',
  getParentRoute: () => rootRouteImport,
} as any)
const DataCleaningRoute = DataCleaningRouteImport.update({
  id: '/data-cleaning',
  path: '/data-cleaning',
  getParentRoute: () => rootRouteImport,
} as any)
const BlitzDayRoute = BlitzDayRouteImport.update({
  id: '/blitz-day',
  path: '/blitz-day',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionsIndexRoute = RegionsIndexRouteImport.update({
  id: '/regions/',
  path: '/regions/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionsCodeRoute = RegionsCodeRouteImport.update({
  id: '/regions/$code',
  path: '/regions/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blitz-day': typeof BlitzDayRoute
  '/data-cleaning': typeof DataCleaningRoute
  '/enrichment': typeof EnrichmentRoute
  '/hubspot-usage': typeof HubspotUsageRoute
  '/icp': typeof IcpRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/settings': typeof SettingsRoute
  '/table': typeof TableRoute
  '/regions/$code': typeof RegionsCodeRoute
  '/regions/': typeof RegionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blitz-day': typeof BlitzDayRoute
  '/data-cleaning': typeof DataCleaningRoute
  '/enrichment': typeof EnrichmentRoute
  '/hubspot-usage': typeof HubspotUsageRoute
  '/icp': typeof IcpRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/settings': typeof SettingsRoute
  '/table': typeof TableRoute
  '/regions/$code': typeof RegionsCodeRoute
  '/regions': typeof RegionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blitz-day': typeof BlitzDayRoute
  '/data-cleaning': typeof DataCleaningRoute
  '/enrichment': typeof EnrichmentRoute
  '/hubspot-usage': typeof HubspotUsageRoute
  '/icp': typeof IcpRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/settings': typeof SettingsRoute
  '/table': typeof TableRoute
  '/regions/$code': typeof RegionsCodeRoute
  '/regions/': typeof RegionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blitz-day'
    | '/data-cleaning'
    | '/enrichment'
    | '/hubspot-usage'
    | '/icp'
    | '/leaderboard'
    | '/login'
    | '/partners'
    | '/settings'
    | '/table'
    | '/regions/$code'
    | '/regions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blitz-day'
    | '/data-cleaning'
    | '/enrichment'
    | '/hubspot-usage'
    | '/icp'
    | '/leaderboard'
    | '/login'
    | '/partners'
    | '/settings'
    | '/table'
    | '/regions/$code'
    | '/regions'
  id:
    | '__root__'
    | '/'
    | '/blitz-day'
    | '/data-cleaning'
    | '/enrichment'
    | '/hubspot-usage'
    | '/icp'
    | '/leaderboard'
    | '/login'
    | '/partners'
    | '/settings'
    | '/table'
    | '/regions/$code'
    | '/regions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlitzDayRoute: typeof BlitzDayRoute
  DataCleaningRoute: typeof DataCleaningRoute
  EnrichmentRoute: typeof EnrichmentRoute
  HubspotUsageRoute: typeof HubspotUsageRoute
  IcpRoute: typeof IcpRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  PartnersRoute: typeof PartnersRoute
  SettingsRoute: typeof SettingsRoute
  TableRoute: typeof TableRoute
  RegionsCodeRoute: typeof RegionsCodeRoute
  RegionsIndexRoute: typeof RegionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/table': {
      id: '/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof TableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/icp': {
      id: '/icp'
      path: '/icp'
      fullPath: '/icp'
      preLoaderRoute: typeof IcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hubspot-usage': {
      id: '/hubspot-usage'
      path: '/hubspot-usage'
      fullPath: '/hubspot-usage'
      preLoaderRoute: typeof HubspotUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enrichment': {
      id: '/enrichment'
      path: '/enrichment'
      fullPath: '/enrichment'
      preLoaderRoute: typeof EnrichmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-cleaning': {
      id: '/data-cleaning'
      path: '/data-cleaning'
      fullPath: '/data-cleaning'
      preLoaderRoute: typeof DataCleaningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blitz-day': {
      id: '/blitz-day'
      path: '/blitz-day'
      fullPath: '/blitz-day'
      preLoaderRoute: typeof BlitzDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regions/': {
      id: '/regions/'
      path: '/regions'
      fullPath: '/regions/'
      preLoaderRoute: typeof RegionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regions/$code': {
      id: '/regions/$code'
      path: '/regions/$code'
      fullPath: '/regions/$code'
      preLoaderRoute: typeof RegionsCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlitzDayRoute: BlitzDayRoute,
  DataCleaningRoute: DataCleaningRoute,
  EnrichmentRoute: EnrichmentRoute,
  HubspotUsageRoute: HubspotUsageRoute,
  IcpRoute: IcpRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  PartnersRoute: PartnersRoute,
  SettingsRoute: SettingsRoute,
  TableRoute: TableRoute,
  RegionsCodeRoute: RegionsCodeRoute,
  RegionsIndexRoute: RegionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
